### ISSUE TITLE
[ENHANCEMENT] Icono de la extensión con los bordes blancos

### ISSUE THREAD

**Issue by ramiro2114** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#10]
básicamente eso que el logo se le ven los bordes blancos como si fuera un jpg en vez de un png nada más, disculpa si no es prioridad, muchas gracias
![Captura de pantalla 2020-11-29 205839](https://user-images.githubusercontent.com/1613097/100557125-ad08b400-3285-11eb-970a-1d2fc4f72a63.png)

**Comment by emilianog94** [comment]
Hola @ramiro2114 , ¡gracias por el reporte!

No había notado que el PNG no era transparente. Lo sumo para corregir en la update 0.5 que se lanza esta misma semana.

Saludos, gracias!

**Comment by emilianog94** [comment]
Testing exitoso, enviado a Chrome Store y Mozilla Addons, ¡muy pronto se actualizará en todos los navegadores!

**Comment by emilianog94** [comment]
Solucionado en la update v0.5 @ramiro2114 ! 
![image](https://user-images.githubusercontent.com/38828911/101053119-2b0ada80-3566-11eb-83c2-e09f7b6aeed8.png)

Cierro el issue, gracias!
