### ISSUE TITLE
[BUG] Dolar erroneo en preguntas frecuentes

### ISSUE THREAD

**Issue by ChescoFishy** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#100]
No se si es un bug pero en la seccion de preguntas frecuentes de la pagina web (https://steamcito.com.ar/preguntas-frecuentes), en la pregunta (El precio que me aparece en Steamcito, ¿es el precio final que llega a mi tarjeta?) aprarece un calculo erroneo del dolar con un dolar desactualizado.

**Comment by emilianog94** [comment]
Hola @ChescoFishy , gracias. Estoy al tanto! 

En los próximos días voy a actualizar el sitio web para traer en tiempo real la cotización del dólar. 
Además de mostrarlo en algunas secciones, voy a hacer que esta sección use la cotización dinámica.

Un saludo!
