### ISSUE TITLE
[BUG] Precio equivalente en pesos no aparece al querer agregar fondos

### ISSUE THREAD

**Issue by VGonKie** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#102]
Al intentar agregar fondos a una cuenta de steam y darle click en el precio en dólares para ver cuál sería el precio equivalente en pesos, este no muestra nada y no se puede volver a clickear para volver a mostrar el precio en dólares

Pasos a seguir para recrear el bug:
1. Dirigirse a steam y verificar de estar logueado a una cuenta argentina
2. Clickear el nombre de usuario en la esquina derecha superior.
3. Clickear el botón de "Ver mi cartera"
4. Clickear cualquier precio en dólares.

Antes de clickear un precio:
![imagen](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/43831866/f30340d4-945f-490c-8530-1c384e44d9d2)
Luego de clickear un precio:
![imagen](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/43831866/7a4f4678-af6b-4df6-ab90-dd513ba04a95)

Navegador usado: Mozilla Firefox 121.0.1 (64-bit)

**Comment by emilianog94** [comment]
Hola @VGonKie 

Muchas gracias por tu aviso, ya pude replicarlo desde mi lado. Efectivamente en la última actualización me faltó un detalle en la versión de Firefox de esta sección. 

Esta misma semana envío a Firefox Addons el parche para arreglarlo.

Un saludo y gracias!

**Comment by emilianog94** [comment]
Solucionado en la versión V3.30 @VGonKie , gracias!
En el transcurso de la semana se actualiza automáticamente a la nueva versión.
