### ISSUE TITLE
[BUG] No me funciona Steamcito en páginas individuales de juegos

### ISSUE THREAD

**Issue by JPnct** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#104]
**Describí el bug**
La conversión de dolar a pesos me funciona en la página principal, pero ya no cuando entro a la página de cualquier juego. Y me pasa con todos los juegos. No con alguno en particular. Entro a la página de algún juego, y no sólo no me figura en la derecha la del dolar que está tomando en el momento para la conversación, que en algún momento me lo supo hacer (no sé si fue con otra versión de steamcito, pero fue hace bastante), si no que tampoco me figura la conversión del precio del juego.
Chrome está actualizado y he intentado hacer la prueba con todas las extensiones deshabilitadas (excepto Steamcito obvio) y no ha habido cambio.
Desconozco desde qué momento empecé a tener este problema, pero me acuerdo que anduvo bien hasta poco después de que dolarizaran la tienda, y luego empecé con este problema.

**Capturas de Pantalla**
En la página principal, todo bien y normal.
![7](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/159466203/be79e5a5-6c34-4427-ba49-c5ac327549ee)

En la página de algún juego, no sólo no me figura a la derecha la equivalencia del dolar, sino que tampoco me figura la conversión del precio (ni siquiera el matecito). Y cuando hago click en el precio en dólar, pasa lo que se muestra en "Ori The Collection" en este ejemplo: desaparece el precio directamente. Y para hacer que reaparezca el precio en dólares, tengo que recargar la página. Porque me permite clickear de nuevo el precio pero nada cambia.
![8](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/159466203/3bf41a4b-d5b3-4122-a8f6-686dc0cd6ae6)

**Información de tu PC**
 - Navegador que estás usando: Chrome 121.0.6167.161 (Build oficial) (64 bits)
 - Versión de la extensión: 3.30

**Comment by emilianog94** [comment]
Hola @JPnct , muchas gracias por tu reporte. 

Pensé que este problema en algunas instalaciones de Chromium estaba solucionado. 

Te pido por favor, para poder entender mejor el origen del problema ya que no puedo replicarlo desde acá

1. Ingresar a cualquier página de juego individual
2. Presionar F12 y clickear en Console. 
3. Refrescar la página
4. Ahí deberían salir errores en rojo:
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/554fcaa9-efa5-41d4-ab15-946a25a2a12e)

Me pasarías la captura de pantalla de esos errores?
Hecho esto que me sirve para ver qué pudo haber pasado, podés eliminar la extensión y reinstalarla y el bug debería estar solucionado. 

Un saludo y aguardo tu respuesta!

**Comment by emilianog94** [comment]
Muchas gracias @JPnct , me re sirve esto que comentaste! Voy a analizarlo para ver si en una próxima versión puedo evitar esta instancia de error. 

Podrías indicarme si eliminando la extensión y reinstalándola desde cero se te arregla?

**Comment by emilianog94** [comment]
Gracias @JPnct !

Entiendo, si vuelve a sucederte te agradecería que me lo reportes por este mismo medio para entender con cuanta frecuencia puede suceder y al momento de investigarlo ver si hay alguna condición específica de la red o del navegador que esté vinculado a replicar este error.

Un saludo!!

**Comment by Squaredude** [comment]
Hola, @emilianog94 !

Hace un tiempo me pasé a Vilvadi (Chromium) y tengo este mismo problema.

En mi caso, tengo que desinstalar y reinstalar la extensión cada vez que cierro el navegador.

### En el carrito:
Sin tocar nada.
Deja de salir todo lo que está abajo del listado de juegos a comprar, aunque sí aparece para cada juego el precio pesificado.
![Screenshot 2024-02-18 105427](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/14142391/3863e010-2f7a-4122-b060-ad25e62d6711)

### En la página de un juego:
Sin tocar nada.
Haciendo esta captura me di cuenta que tenía SteamDB instalado y pensé que tal vez eso hacía alguna "interferencia". Ambas capturas son del mismo juego, con y sin la extensión de SteamDB (habíendo cerrado y abierto el navegador, desintalado y reinstalado Steamcito de por medio).
(Con SteamDB)
![Screenshot 2024-02-18 105533](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/14142391/0e024b3d-8585-405e-bc80-ef218297446f)

(Sin SteamDB)
![Screenshot 2024-02-18 105745](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/14142391/eabe5b6d-a120-4b24-8d14-1ddaf6874029)

No parece haber problemas entre las extensiones, por lo menos.

### En la página principal de Steam:
Sin tocar nada.
![Screenshot 2024-02-18 105838](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/14142391/7f37dab2-d81f-4fdd-89f0-f340bdb8614e)

**Comment by emilianog94** [comment]
Hola @Squaredude , gracias por sumarte al reporte. Me sirve mucho esto que me indicaste ya que me muestra que en estos casos no les está cargando los scripts globales que aplican a todas las páginas, sino que sólo está cargando los script específicos de una página particular.

Lo que se me ocurre para solucionar esto (que lamentablemente no estoy pudiendo replicar desde mi lado desde Vivaldi o Chrome), es llamar a todos los scripts globales en todos los patrones de URL posibles. 

Como en tu caso es mucho más fácil de replicar ya que ocurre cada vez que cerrás el navegador, ¿te parece bien si preparo esta versión y te paso la branch para que la instales manualmente y me indiques si se arregla? 

Gracias

**Comment by Squaredude** [comment]
Dale, no hay drama!

**Comment by emilianog94** [comment]
Hola @Squaredude !

Hice una pequeña modificación en el manifest en la siguiente rama:
https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/tree/hotfix/v332

Te indico el paso a paso para probarla: 

1. Descargar el ZIP desde el botón verde Code - Download ZIP
2. Descomprimilo donde desees
3. Ingresá desde tu navegador a vivaldi://extensions/
4. En el extremo superior derecho activá "Modo de Desarrollador"
5. En el extremo superior izquierdo clickeá en el botón "Cargar extensión sin empaquetar"
6. Buscá la carpeta donde descomprimiste el ZIP, ingresá a chrome_extension y seleccioná la carpeta
7. Desactivá la extensión V3.30

El resultado final debería ser así: 
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/cd561675-0551-4568-ae7b-c5fe64b07afa)


En esta versión hice un pequeño ajuste en la sección Cart: https://store.steampowered.com/cart/

Me podrías indicar (con un juego agregado al carrito) si el resto de las secciones sigue tirando el mismo error y si Cart se solucionó? 
Muchas gracias desde ya!

**Comment by Squaredude** [comment]
Con esta versión parecen haberse solucionado todos los problemas de las secciones que indiqué en mi comentario anterior (página principal, carrito, página de juego). No aparecen errores en la consola.

También cerré y abrí el navegador, y la extensión siguió funcionando sin problemas.

**Comment by emilianog94** [comment]
Gracias por tu pronta respuesta @Squaredude !

Te confirmo que no modifiqué código de ninguna otra sección, lo cual indicaría que posiblemente haya algo corrupto en la instalación de la extensión original desde Chrome Web Store.

Podrías usar esta versión que te pasé (3.32) unos días y comentarme si se vuelven a replicar los problemas? En el caso de que vuelvan a replicarse, me serviría mucho que me indiques si la sección Carrito es la única que no tira errores!

**Comment by Squaredude** [comment]
Por las dudas te aclaro ahora el comentario anterior: no tiró errores en la consola en ninguna de las secciones que visité (página principal, carrito, página de juego).

>Podrías usar esta versión que te pasé (3.32) unos días y comentarme si se vuelven a replicar los problemas? En el caso de que vuelvan a replicarse, me serviría mucho que me indiques si la sección Carrito es la única que no tira errores!

Dale, no hay problema. En unos días reporto si hay o no errores.

**Comment by Squaredude** [comment]
Hola, @emilianog94 !

Todavía tengo la versión que me pasaste y te puedo confirmar que hasta ahora no he tenido ningún error, ni tuve que reinstalarla. Todo aparece como corresponde en todas las secciones que mencionamos antes.

**Comment by emilianog94** [comment]
Hola @Squaredude , gracias por mantenerme al tanto! 

Lamentablemente esto parece ser un indicio de un problema en la caché/instalación, ya que en el caso de replicar el error debería haber fallado en el resto de las secciones!

Te pregunto, si ahora mismo desactivás temporalmente este ZIP que te pasé y reactivás la extensión original de Chrome Web Store, ¿el error persiste? 

Muchas gracias por tu tiempo desde ya

**Comment by Squaredude** [comment]
Bueno, el tema es que cuando instalé la versión para testear, me apuré y en vez de desactivarla, la desinstalé. 😅

Ahora instalé la última versión estable (3.31 en Chrome) y desactivé la de prueba (3.32), y no estoy viendo errores tampoco.

Cerré y abrí el navegador, para intentar replicar el problema que tenía antes, y no puedo volver a replicarlo. La consola no tira errores tampoco. 🤷🏻‍♂️

Todo pareciera andar correctamente.

Estoy a tus órdenes.

**Comment by emilianog94** [comment]
Buenas @JPnct @Squaredude , les confirmo que pude trazar la causa exacta del error y la nueva versión Steamcito v3.42 que acaba de ser lanzada soluciona este bug en fichas de producto. Se va a estar actualizando automáticamente en sus navegadores el día de hoy. 

¡Cualquier cosa me avisan! Muchas gracias
