### ISSUE TITLE
[FEATURE] Filtrar juegos que tengan precio regional

### ISSUE THREAD

**Issue by to-ty** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#105]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
No saber que juegos tienen precio regional sin ver cada uno individualmente

**¿Qué te gustaría que ocurra?**
Añadir un filtro a la búsqueda de Steam que permita filtrar por juegos que tengan precio regional adecuado o más barato 

**Comentarios Adicionales**
No sé si es posible hacerlo, pero me gustaría para poder encontrar y apoyar a los devs que les importó el cambio de moneda y no lo dejaron tal cual

**Comment by emilianog94** [comment]
Hola @to-ty !

Te confirmo que estoy trabajando en ello. Estoy creando una herramienta que analiza todos los juegos de Steam y toma sus precios en LATAM y en Estados Unidos para consolidar una base de datos de juegos con precios regionales bajos en nuestra región.

En una primera etapa tomará todos los juegos que están muy baratos, es decir aquellos publishers que fueron un paso más allá y lo pusieron aún más barato que el sugerido por Valve. (Ejemplo: Hades)

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/611044c2-e1b8-490c-a5a7-2479c0ccd217)


Consolidada etsa base de datos voy a mostrarla en una sección específica del sitio web y voy a agregar un acceso directo en la extensión para poder visualizarlo desde la tienda de Steam.

No puedo darte una fecha estimativa para concretar esto ya que estoy aprendiendo a la par, pero ya empecé a trabajarlo!

**Comment by emilianog94** [comment]
Estimo contar con una versión inicial que consiste en una curaduría de juegos con buen precio regional actualizada cada 24hs en la web a mediados de Marzo.

**Comment by emilianog94** [comment]
Hola @to-ty !
Te confirmo que elaboré una versión inicial de esto en el siguiente link: 
https://steamcito.com.ar/tops/100-juegos-superregionales-steam-spring-sales-2024

Posterior a las Steam Sales espero elaborar algo más automático y dejarlo siempre fijado en ese link para que se actualice todos los días. 

Un saludo!
