### ISSUE TITLE
[FEATURE] Impuesto Predeterminado

### ISSUE THREAD

**Issue by FedeBurgos** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#110]
Al modificar los impuestos en las Opciones de impuestos dentro de la página de Steam, luego debo fijarme cuál es el porcentaje de impuestos para ponerlos de una manera fija.

Estaría bueno una opción de "valor predeterminado" que fije el porcentaje agregado de impuestos al precio final al valor actual en caso de que se hagan modificaciones de este valor manualmente.

**Comment by emilianog94** [comment]
Hola @FedeBurgos !

Perdón, no entendí bien tu consulta. 
Al momento de modificar los impuestos desde el panel lateral estarías reemplazando la base que ofrece la extensión. 

¿Para qué sería esta opción de Valor Predeterminado? ¿Para tenerlo a la vista? 
Por otro lado, ¿esto lo pensaste en el caso de modificar el valor impositivo y que por ejemplo el gobierno aumente los impuestos así tu personalización no queda desactualizada? 

Un saludo!

**Comment by FedeBurgos** [comment]
Hola @emilianog94 

El Valor Predeterminado sería para volver al impuesto base que ofrece la extensión en ese momento. Esto lo pensé en un momento que modifiqué el valor impositivo desde el panel lateral y al querer volver al actual, o sea, al impuesto base de la extensión tuve que modificar de nuevo el panel lateral.

Si el valor en el panel lateral queda fijo, en caso de que el gobierno modifique el porcentaje de los impuestos, la personalización quedaría desactualizada.

Saludos

**Comment by emilianog94** [comment]
Hola @FedeBurgos , te confirmo que en la nueva versión de Steamcito v3.50 que se lanzará en el transcurso de hoy se hizo un rework de esta funcionalidad para evitar cualquier tipo de desincronización causado por una personalización del usuario. 

A partir de ahora el porcentaje de impuestos es fijado automáticamente por Steamcito de acuerdo al método de pago seleccionado, de manera que ya no hay de qué preocuparse para tener siempre todo actualizado. 

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/06d56f24-3bcc-4605-a218-21759d725eff)

Espero que esto resuelva tu sugerencia, cualquier cosa podés volver a abrir el issue. 
Un saludo y gracias!
