### ISSUE TITLE
[BUG] Recarga de saldo de la cartera de Steam

### ISSUE THREAD

**Issue by SrPY** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#111]
Hice una recarga de 10 dólares y la verdad no cuadra el precio pesificado. El que has establecido no es correcto, pero tampoco se puede tomar el dolar tarjeta como referencia ya que no da el número. El monto final que terminé pagando vía tarjeta virtual de Mercadopago fue un 1,9% más que tu referencia. No sé si se deba a algo extra que te cobre MP o la verdad que no sé que decir. No es un bug como tal, pero es para que tengas en cuenta este dato, ya que me imagino que en las otras cantidades pase lo mismo y te cobren ese 1,9% extra.
![1](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/62674581/7f00130c-bb70-40ef-9d91-ac43b35a10df)
![2](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/62674581/756a2ba1-dc0a-4e51-95dc-99c8617763f2)

**Comment by SrPY** [comment]
Se me olvidaba, te pongo una tercera captura para mas claridad, tu que entiendes más... Ahhh entendí, listo listo es un impuesto agregado de Mercado pago... Aquí te paso otra captura debajo de la que te dejé para mas claridad... Te cobran un 2% extra MP por si fuera poco los impuestos que te clavan. Con todo lo que te pasé espero tengas una referencia mejor de precios, qie lío hermano.
![3](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/62674581/84e2ed5b-d65a-42cf-92a8-c8604eaf5846)
![4](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/62674581/5bf163cb-c5e0-4d5c-a454-c194b7ea8704)

**Comment by SrPY** [comment]
A mi me han visto la cara hermano... Acabo de cargar otros $20, 10 y 10 y mira esto compa. In crescendo si cargas mas de 10 usd.
![5](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/62674581/4d5f9309-11e4-4ac2-92b4-81ca6d045985)

**Comment by emilianog94** [comment]
Hola @SrPY !

Steamcito ofrece como cotización del dólar un promedio de todos los bancos. 
Algunas tarjetas cobran más que otras.

Por esta razón es que el mes pasado lancé una funcionalidad que toma la tarjeta más cara y la más barata para que sepas el mínimo y el máximo, la podés ver desde el carrito.

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/83a36379-20df-4de2-9bff-5d9f2c3ad412)

Se encuentra en mis planes agregar al sitio web una tabla con la cotización del dólar de las diferentes billeteras virtuales del país, entre ellas MercadoPago. 

Un saludo y gracias!

**Comment by SrPY** [comment]
Tu trabajo es excelente hermano. Siemplemente te dejé lo de arriba para que tengas una estimación de lo que hace MP en este caso... Gracias por la ayuda que nos brindas.
