### ISSUE TITLE
[BUG] Steam lanzó un nuevo diseño de carrito y Steamcito no funciona

### ISSUE THREAD

**Issue by zaidac** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#112]
cuando voy a mi carrito y quiero comprar un juego con mi saldo de steam y mi tarjeta no me aparece esta funcion
Una descripción del problema

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. busque mi juego
2. lo añadi al carrito
3. fui al carrito y esta funcion no estaba
![Captura de pantalla (2)](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/137930505/5fef84f6-2f2c-40a8-b4ba-e4a8e410674e)

**Información de tu PC**
 - Navegador que estás usando: microsoft edge
 - Versión de la extensión: 3.31

**Comentarios adicionales**
Cualquier otro comentario que creas relevante para entender mejor el problema.

**Comment by emilianog94** [comment]
Hola @zaidac ! Gracias por avisarme, recién lo veo. 

Hace pocas horas Steam lanzó el nuevo diseño del carrito: https://steamcommunity.com/games/593110/announcements/detail/4149575031731807336

Voy a tener que ponerme a trabajar para reestablecer la funcionalidad de Steamcito, espero tenerlo para la próxima semana como mucho. 
Un saludo!

**Comment by zaidac** [comment]
De nada siempre es un placer ayudar

**Comment by emilianog94** [comment]
Funcionalidad iniciada en https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/tree/feature/v340

Para el martes va a estar lanzada la actualización inicial del carrito donde se reestablecerán las funcionalidades primarias de cálculo y cotización.

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/f719a043-5648-4b36-a881-27d965db7582)

**Comment by emilianog94** [comment]
Olvidé actualizar este issue jeje, ya está solucionado del todo con el lanzamiento de V3.40 la semana pasada. 

Cierro! 🙂
