### ISSUE TITLE
[BUG] No encuentro como cambiar los impuestos personalizado.

### ISSUE THREAD

**Issue by Jealdagi** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#115]
No estoy seguro si esto es un bug pero no encuentro ningun otro lugar donde preguntar por esto, lo lamento si es una perida de tiempo. Hace tiempo que no uso steam y el porcentaje de impuesto cambio mucho desde entonces  pero ya no me aparece la ventana naranja en la seccion de la compra donde podia cambiar el porcentaje personaliza asi que ahora se quedo incorrecto. Y he buscado pero no logo encontrar ningun menu de opciones para configurarlo.
Perdon de nuevo y sientance libres de ignorar esto si no se supone que pregunte por aqui o si lo hice mal.

**Comment by emilianog94** [comment]
Hola @Jealdagi !

Te confirmo que podés acceder al personalizador de impuestos clickeando en el matecito arriba de todo a la derecha:
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/8703ae9a-891b-40a8-835c-998fecc3dcc4)

La opción de personalizar desde el Carrito no va a volver pronto porque cambió el diseño de Steam y necesito revisar dónde agregar nuevamente esa info.

Un saludo! Cualquier cosa volvé a comentarme

**Comment by Jealdagi** [comment]
Muchas gracias! No lo envíe dos veces por error por cierto, es solo que no
sabía bien si esto contaba como bug, y no me había dado cuenta de la opción
de "blank issue" así que lo envie otra ves por si no respondía al otro por
no ser un bug. Perdone las molestias.
