### ISSUE TITLE
[BUG] Carrito de compra precio

### ISSUE THREAD

**Issue by tobiasvasquez** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#119]
**Describí el bug**
Una descripción del problema

Cuando te dirigis al carrito, en el lugar del checkout, tenes unos tags <span> que no estan renderizando nada

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí esta URL : https://store.steampowered.com/cart
2. Hice X acción:  Mire el precio 
3. Apareció el error

**Capturas de Pantalla**
De ser necesario, agregá capturas del problema
![Screenshot from 2024-03-19 01-45-05](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/54642010/f298161b-0fb5-434f-b37f-c1cf6782a516)

**Información de tu PC**
 - Navegador que estás usando: Chrome 
 - Versión de la extensión: 3.41
 - S.O : Ubuntu 23.10

**Comentarios adicionales**
Cualquier otro comentario que creas relevante para entender mejor el problema.

**Comment by emilianog94** [comment]
Hola @tobiasvasquez !

Te confirmo que intenté resolver este inconveniente sin embargo hay un problema ya que este nuevo carrito de Steam no permite insertar elementos HTML. Como los emojis retrocompatibles son elementos HTML en vez de un caracter de Unicode, es imposible renderizarlos en tal contenedor.

Temporalmente para evitar este error de visualización lo que hice fue eliminar los emojis de este contenedor en el caso de que el usuario utilice emojis retrocompatibles.

Esto estará activo en Steamcito v3.50
Un saludo y gracias!
