### ISSUE TITLE
[BUG] Bundles se muestran en dólares

### ISSUE THREAD

**Issue by eruizc-dev** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#120]
**Describí el bug**

Los bundles en el Steam Search aparecen en dólares

**¿Qué pasos seguiste para llegar al bug?**

https://store.steampowered.com/search/?term=wrc

**Capturas de Pantalla**

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/58179604/c652195c-00cf-4a89-bd04-791bb4c39998)

**Información de tu PC**

 - Navegador que estás usando: Firefox 123.0.1
 - Versión de la extensión: 3.31

**Comment by emilianog94** [comment]
Hola @eruizc-dev , muchas gracias por tu aviso! 

Acabo de verificarlo y efectivamente se debe a que nunca le agregué a la sección /search la posibilidad de reprocesar bundles de forma asincrónica. Esto es necesario ya que los precios de las bundles son dinámicos para cada usuario de acuerdo a los juegos que posea en su biblioteca, y lo que hace Steam es cargar el precio posterior a la carga inicial del sitio. 

Lo dejo abierto y lo tengo en cuenta para sumarlo en la próxima actualización. 
¡Un saludo y gracias!

**Comment by eruizc-dev** [comment]
Qué genio Emi, gracias a vos por todo el laburo que le ponés a esto

**Comment by emilianog94** [comment]
Hola @eruizc-dev , te confirmo que esto fue arreglado en Steamcito v3.50 que se va a lanzar en el transcurso de hoy. 

Ya no debería existir el inconveniente en esta nueva versión, por favor si llegás a notar algo raro avisame!

Un saludo y gracias
