### ISSUE TITLE
[BUG] No funciona Steamcito en páginas individuales de juegos

### ISSUE THREAD

**Issue by RoAriel** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#122]
**Descripción el bug**
No se muestra la conversión de la moneda entrado a un juego X, en el home de steam se ven pero al ingresar no.

**¿Qué pasos seguiste para llegar al bug?**

1. Abrí esta URL [Steam](https://store.steampowered.com/)

[![home.png](https://i.postimg.cc/9fDN6YhF/home.png)](https://postimg.cc/sBRcSSxt)

3. Busque el Elden Ring (en la barra de búsqueda aparece el precio en pesos)

[![home.png](https://i.postimg.cc/43kb4D7M/home.png)](https://postimg.cc/xX5btFPy)

5. Entrando en el juego, se ve que aparece el precio en dólares, y si le hago el click sobre el precio desaparece

[![home.png](https://i.postimg.cc/KzL7CLPd/home.png)](https://postimg.cc/S2SzMntr)

**Información de tu PC**

 - Navegador que estás usando: 
 Brave está actualizado. [Versión 1.64.109 Chromium: 123.0.6312.58 (Build oficial) (64 bits)](https://brave.com/latest/)

 - Versión de la extensión: 3.41

**Comment by emilianog94** [comment]
Hola @RoAriel , muchas gracias por esto, me lo reportaron vía Twitter y lo estoy trabajando y creo haber encontrado la solución. Te hago unas consultas que me servirían mucho: 

1. El error también te ocurre en juegos de tipo "Sub"? 
Ejemplo: https://store.steampowered.com/sub/427289/

2. El error también te ocurre en juegos de tipo "Bundle"? 
Ejemplo: https://store.steampowered.com/bundle/33369/Borderlands_Collection_Caja_de_Pandora/


Muchas gracias desde ya!

**Comment by RoAriel** [comment]
Hola @emilianog94, genio antes que nada.

1. El error también te ocurre en juegos de tipo "Sub"?  **SI**

[![sub.png](https://i.postimg.cc/fWGRYL8V/sub.png)](https://postimg.cc/NLxtcgqt)

2. El error también te ocurre en juegos de tipo "Bundle"? **NO**
[![sub.png](https://i.postimg.cc/cLjkXrbn/sub.png)](https://postimg.cc/qNsG7M0J)

Gracias por tu trabajo.

**Comment by RoAriel** [comment]
Genial! 

Gracias por tu trajo!

**Comment by emilianog94** [comment]
Gracias a vos! La versión Steamcito v3.42 acaba de ser lanzada y se actualizará automáticamente en el transcurso de hoy, cualquier cosa me podés volver a avisar!
