### ISSUE TITLE
[FEATURE] Hacer una mini calculadora web mobile en la página de Steamcito

### ISSUE THREAD

**Issue by Squaredude** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#124]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Actualmente es muy difícil conseguir extensiones en el celular, por lo que si uno no está en la PC no puede ver los precios rápido.

**¿Qué te gustaría que ocurra?**
Steamcito.com.ar podría tener una sección donde se pueda colocar el precio de un juego y que se muestren los cálculos con valores de dólar actualizados, parecido a lo que muestra la extensión en la PC (el espectro de las tarjetas caras/baratas y el dólar cripto). La misma sería para usuarios de celular.

**Alternativas que hayas considerado**
Hacer el cálculo a mano. 😂

**Comentarios Adicionales**
No creo que sea una gran prioridad, pero sería útil para vagos como yo.

**Comment by emilianog94** [comment]
Hola @Squaredude , gracias por la sugerencia!

Por el momento no había pensado en algo por el estilo ya que resulta algo molesto tener que entrar a un sitio de terceros para calcular el precio. (En sí ese sería el problema que Steamcito viene a resolver) 

Voy a evaluar esto que comentás como una opción de fallback. A su vez te confirmo que hace unos meses Firefox liberó la posibilidad a los desarrolladores de publicar complementos para Android de manera que se pueda instalar la extensión en el celu. Esa es una alternativa con la cual posiblemente en algún momento vaya a experimentar!

¡Un saludo y gracias!

**Comment by emilianog94** [comment]
@Squaredude  Se que esto es VIEJÍSIMO pero te confirmo que estoy hace unas semanas laburando en ello y este mes se lanza la calculadora web que engloba diferentes métodos de pago!

**Comment by emilianog94** [comment]
La calculadora ya está en producción, procedo a cerrar el issue! 🫡
https://steamcito.com.ar/
![image](https://github.com/user-attachments/assets/d620951c-4fa2-4132-b534-8e8c059b210e)

**Comment by Squaredude** [comment]
Genioooo! Mil gracias!!!!
