### ISSUE TITLE
[BUG] Steamcito no funciona en el carrito después de cerrar el navegador (Vivaldi/Chromium)

### ISSUE THREAD

**Issue by Squaredude** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#125]
**Describí el bug**
Nuevamente el precio no se muestra en el carrito luego de cerrar el navegador.

**¿Qué pasos seguiste para llegar al bug?**
1. Instalar la extensión (versión 3.42): https://chromewebstore.google.com/detail/steamcito-steam-con-impue/fcjljapncagfmfhdkccgnbkgdpbcefcj
2. Cerrar el navegador
3. Abrir el navegador
4. Abrí esta URL https://store.steampowered.com/cart
5. La extensión no convierte los precios y en la consola aparece un error (captura abajo)

**Capturas de Pantalla**
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/14142391/f0043441-8881-40f3-8306-d5607f741272)

**Información de tu PC**
 - Navegador que estás usando: Vivaldi (Chromium) 6.6.3271.55 (Stable channel) (64-bit) 
 - Versión de la extensión: 3.42

**Comentarios adicionales**
La extensión funciona cuando la instalación de la misma es "fresca", por lo que el workaround anterior de desinstalarla y reinstalarla sin cerrar el navegador aún funciona bien.
Adicionalmente, las otras páginas de Steam no parecen afectadas, aunque en la página principal (en la consola) aparece otro error. No sé si habría que armar otro issue, lo dejo acá:

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/14142391/7e84c91d-9808-418b-9b47-44b2cfe1ae9d)
(No parece afectar la página en sí, porque muestra los precios correctamente.)

**Comment by emilianog94** [comment]
Gracias por el aviso! Esto es muy similar a lo acontecido acá https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/issues/122 , voy a revisarlo ya que seguramente sea aplicar el mismo fix a esa sección. 

¡un saludo!

**Comment by emilianog94** [comment]
Hola @Squaredude , te confirmo que el fix fue enviado a Steamcito v3.50 que se va a lanzar en el transcurso de hoy.

Apenas se actualice la extensión esto no debería volver a ocurrir. En el caso de que vuelva a ocurrir por favor avisame!

Un saludo y gracias por tu reporte
