### ISSUE TITLE
[FEATURE] Mostrar el precio que tiene el juego en otras tiendas de keys.

### ISSUE THREAD

**Issue by FerminAlvarez** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#126]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Ahora que Steam está dolarizado, al mirar el precio de un juego busco a ver si en alguna de las otras páginas de ventas de keys está más barato.

**¿Qué te gustaría que ocurra?**
Me gustaría que una vez estés en la pantalla del juego, aparezca al lado el precio al que se vende en otras tiendas.

**Alternativas que hayas considerado**
Actualmente utilizo Allkeyshop, que para determinado juego muestra todos los precios en las distintas tiendas. Tal vez se podría integrar para directamente obtener la información desde esa página.
Si bien esto ya es algo extra, estaría buenísimo por ejemplo poder organizar la wishlist en base a precio más barato de otras tiendas. Entiendo que esto es complicado por el tema de la cantidad de peticiones a la página.

**Comentarios Adicionales**
![imagen](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/40571267/e7bc2cd9-b2d3-4cf2-bd54-9f8aa5971e2f)

**Comment by emilianog94** [comment]
Buenas @FerminAlvarez !

Desde ya te agradezco por tu sugerencia!
Esto de mencionar revendedores como los que aparecen en https://www.allkeyshop.com/ (third party resellers) es algo que no planeo hacer ya que muchos de estos se encuentran asociados a maniobras ilegales/fraudulentas que perjudican a los publicadores de videojuegos.

Sin embargo estoy al tanto de que ya existe una extensión desarrollada por un tercero que hace exactamente esto:
https://www.reddit.com/r/Argaming/comments/1ba6was/ori_5600_final_m%C3%A1s_barato_que_en_el_hist%C3%B3rico/

En el caso de querer usarla te recomiendo que lo hagas bajo propio riesgo ya que, a diferencia de Steamcito, **no es una extensión de código abierto.**

---

Por último lo que sí me parece interesante de lo que comentás es la posibilidad de incluir solamente revendedores oficiales autorizados como los siguientes:
- Humble Store
- Indie Gala
- Fanatical

¡Podría ver la posibilidad de desarrollar algo de este tipo en el futuro! 

Un saludo y gracias!

**Comment by emilianog94** [comment]
Hola @FerminAlvarez , procedo a cerrar el issue porque entiendo que la extensión Checkey resuelve a la perfección la interesante feature que comentaste, y me sería medio redundante recrear algo que ya existe :D 

Un saludo y gracias
