### ISSUE TITLE
[FEATURE] Sugerencias experiencia usuario

### ISSUE THREAD

**Issue by AlejandroJorba** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#127]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Sugerencias para mejorar la experiencia de usuario:
- El div que muestra las secciones es muy invasivo
- Es realmente útil mostrar la sinopsis del juego? Siento que toma demasiado espacio (creo que la principal función es hacerle saber al usuario las ofertas y precios, en caso de interesarle el precio entrará a ver de que trata el juego más en profundidad)
- Las cards siento que son muy grandes, quizas haya alguna posibilidad para hacerlas más pequeñas
- El "ver en steam" es demasiado invasivo? Mucho color verde? 

En realidad vine a escribir acerca de la primera sugerencia pero dejo algunas más que podrían llegar a modificarse o someterse a votación para ver que opinan los usuarios. 

**¿Qué te gustaría que ocurra?**
- Quizás ocultar el div de "secciones" cuando se scrollee y poner al costado un botoncito para subir hasta arriba (?)

**Comentarios Adicionales**
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/74878915/614d70ec-87cd-4816-a24d-ec0472780208)

// Sugerencia
1era opcion
Sin hover:
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/74878915/63e1ab44-a370-4fb9-abaf-421db5d78ee5)
Hover:
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/74878915/21cddb74-0a2f-48c8-a0f5-d059efee9f62)
 
2da opcion
Sin hover:
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/74878915/e1832f0c-a0d4-4889-b496-d0ca0951e607)
Hover:
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/74878915/418b8e8b-5091-47a8-9e26-7d2636b986db)

En mi opinión se ve más limpio y no ocupa tanto espacio la card aunque quizás pueda haber otra forma de hacerlo, espero que sea de utilidad!

**Comment by AlejandroJorba** [comment]
@emilianog94  Muchas gracias a vos por la respuesta! No sabía que recién lo sacabas, me imagino que estuviste explotado esos días jajaja, la idea es tratar de dar ideas que puedan ser útiles y copadas, espero que te hayan servido al menos para darle una vuelta de rosca, cualquier cosa chifla y en lo que se pueda ayudar acá estamos

**Comment by emilianog94** [comment]
Buenas @AlejandroJorba , te confirmo que tuve en cuentas tus sugerencias!

Con motivo del festival de rejugabilidad infinita próximamente voy a estar subiendo una sección con lo mejor de este evento (Posiblemente el miércoles)

Te paso un preview de cómo está quedando!

https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/92a2333d-86ed-4a10-8c5f-b120eec55aeb

Un saludo y gracias desde ya por tus sugerencias!

**Comment by AlejandroJorba** [comment]
Naaaaaaaaa una masa loco, te quedó espectacular, te fijaste que no traiga todos los videos de una? Porque sino seguramente tarde en cargar la página

**Comment by emilianog94** [comment]
Así es @AlejandroJorba !

Los vídeos sólo se cargan en el DOM al hacer hover (o pulsar en Mobile), y trae solamente micro-gameplays de 6 segundos con peso inferior a 1mb para darte una mínima idea de la jugabilidad.
