### ISSUE TITLE
[FEATURE] Seleccionar forma de pago preferida

### ISSUE THREAD

**Issue by sixGdie** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#128]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Con la opción de hacer la compra con dolar crypto, estaría bien poder tener la funcionalidad de poder elegir el método de pago preferido para así poder saber cuál sería el precio final del juego dependiendo de la forma de pago.

**¿Qué te gustaría que ocurra?**
Poder seleccionar la forma de pago preferida en la extensión.

**Alternativas que hayas considerado**
Ninguna

**Comentarios Adicionales**
Ninguno

**Comment by sixGdie** [comment]
Por lo que veo esto ya está aplicado de alguna forma y no lo había visto, asique cierro. Excelente trabajo Emi !

**Comment by emilianog94** [comment]
Hola @sixGdie 

Te agradezco por tu sugerencia! 
Actualmente existe una funcionalidad pero que es para personalizar el % de impuesto nacional/provincial. 

Te confirmo que estoy trabajando de forma activa en una nueva versión que te permita a través de un menú desplegable poder elegir tu método de pago favorito para que Steamcito te lo configure automáticamente. Vas a poder elegir entre Crypto, MEP y Tarjeta. 

Estimo poder lanzar esta nueva actualización durante la primer semana de Mayo.
Dejo el issue abierto mientras tanto, un saludo!

**Comment by emilianog94** [comment]
Hola @sixGdie , te confirmo que esta funcionalidad fue adicionada a Steamcito v3.50 y se estará actualizando automáticamente el día de hoy.

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/aaf09e7c-2bae-41c4-b88f-fdcb52aa37b9)

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/c02e290e-726f-48dd-9e0d-5c75dc791550)

Si notás algo raro apenas esté la update podés avisarme.
Un saludo y gracias!
