### ISSUE TITLE
[FEATURE] Sugerencia experiencia de usuario en el top

### ISSUE THREAD

**Issue by alanmoyano** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#131]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Me parece medio raro que al darle click al video en las cards de los juegos no te lleve a la página (teniendo en cuenta que el cursor sale en pointer), sino que tenés que hacerlo en el título, no es nada grave obvio, pero creo que te ahorra ese primer click en el que pensás que va a llevarte y después buscás donde si tenés que dar click para que te lleve.

**¿Qué te gustaría que ocurra?**
Que al darle click al video te lleve a la página de steam del juego

**Comentarios Adicionales**
<video src="https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/102170281/52e8966f-99d5-442c-bdcc-a302068f4860"></video>

**Comment by emilianog94** [comment]
Hola @alanmoyano , muchas gracias por tu sugerencia!

Me pasó hoy a la tarde que quería usar la página y me basaba en los microgameplays para ver si los abría en Steam para examinarlos mejor. Tal como decís es algo molesto tener que mover el mouse para abrirlo. 

Te confirmo que acabo de deployear una update con optimizaciones varias en la página, incluyendo esta misma que comentaste. 
¡Avisame cualquier otra cosa que notes para mejorar!
