### ISSUE TITLE
[BUG] Mandar reclamo a Capcom

### ISSUE THREAD

**Issue by Riquimaru** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#133]
**Describí el bug**
[Una descripción del problema
](https://www.capcom-support.com/hc/en-us/requests/new) esta es la dirección, la que tiene actualmente da error
**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí esta URL http://........
2. Hice X acción
3. Apareció el error

**Capturas de Pantalla**
De ser necesario, agregá capturas del problema

**Información de tu PC**
 - Navegador que estás usando: 
 - Versión de la extensión:

**Comentarios adicionales**
Cualquier otro comentario que creas relevante para entender mejor el problema.

**Comment by emilianog94** [comment]
Hola @Riquimaru , gracias por tu comentario!

Lamentablemente desde mi lugar no es posible hacer algo porque las URL de contacto / Mails  son suministradas por el publicador del videojuego a Steam, es decir ellos son los responsables de que esté correcto o actualizado. 

Un saludo!
