### ISSUE TITLE
[BUG] Error de precio en ARS cuando el monto supera un millón

### ISSUE THREAD

**Issue by FrancoRav** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#134]
**Describí el bug**
Cuando el monto supera el millón de pesos (imagino que es lo que está pasando), se muestra el precio incorrecto. Por ejemplo, con el botón de Añadir todos los DLC al carro en Los Sims 4, se muestra "ARS$ 1.869,12", cuando debería mostrarse "ARS$ 1.869.12x,xx"

**¿Qué pasos seguiste para llegar al bug?**
1. Abrí https://store.steampowered.com/app/1222670/The_Sims_4/
2. Clickear ver todo en la sección de DLC
3. En el cuadro del precio al lado del botón de añadir todos al carrito, se muestra incorrectamente

**Capturas de Pantalla**
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/76495139/c38360e6-68ae-40b5-953b-da44ede0d92d)
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/76495139/47d66ed3-a4c5-41f2-8b90-9e36ecec5517)

**Información de tu PC**
 - Navegador que estás usando: Brave
 - Versión de la extensión: 3.50

**Comentarios adicionales**
N/A

**Comment by emilianog94** [comment]
Hola @FrancoRav , muchas gracias por notar esto, nunca lo vi!

Voy a revisarlo para que esté solucionado en la próxima actualización. 
Un saludo y gracias!!

**Comment by emilianog94** [comment]
Solucionado, va a estar lanzado hoy en la nueva versión v3.51

![fix](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/062dd2b9-d339-45f9-92ff-d302e2869096)

Cierro el issue, cualquier futuro problema asociado a esto por favor avisame. 
Muchas gracias nuevamente!
