### ISSUE TITLE
[BUG] No aparece el boton "Solicitar precio regional"

### ISSUE THREAD

**Issue by FrachoG** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#136]
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/122075028/105a6509-9247-4e9d-8272-9966b3ad01ca)
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/122075028/1a2332d2-d25a-473c-ab6f-594f8c492049)
Tanto en juegos con precio "alto" o "inexistente"
Me fije que en tu changelog no lo habías cambiado y tengo la extensión actualizada, así que creo que es un bug o steam cambio algo

**Comment by emilianog94** [comment]
Hola @FrachoG ! Todo bien? 

Ahí acabo de corroborarlo. Justo en el juego que mencionaste su publicador no cargó ningún medio de contacto público. 

https://store.steampowered.com/app/47810/Dragon_Age_Origins__Ultimate_Edition/
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/476bb9f3-bacb-4d2a-9b9c-76180a1b82d7)

La funcionalidad se encuentra activa solamente en aquellos juegos que tienen precio regional en rojo (Inexistente) en los que exista un medio de contacto. Los medios de contacto son de carácter obligatorio desde hace casi 10 años tengo entendido, este juego es bastante viejito y seguramente en la época en qué salió esto no era obligatorio. 

En cualquier otro juego con precio regional inexistente que abras (Por ejemplo el FIFA), deberías ver la funcionalidad correctamente: https://store.steampowered.com/app/2195250/EA_SPORTS_FC_24/

¡Avisame cualquier cosa!
Un saludo.
