### ISSUE TITLE
[FEATURE] Historial de precios (precio más bajo)

### ISSUE THREAD

**Issue by AlejandroJorba** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#137]
Buenas! Estaba justo viendo un video sobre recomendaciones de las ofertas y el flaco tiene una extensión donde figuran los precios de otras regiones y también el mejor precio que tuvo, será que se puede agregar algo parecido (sin lo de la región, al pedo eso). Tengo amigos que son unos pajeros y no entran a steamdb al igual que hay gente que no lo conoce, creo que sería re útil, inclusive colocar una redirección para poder ver el chart del historial d precios en caso de que queras verlo

Imagen:
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/74878915/27d67683-f611-4ba2-b0e4-f54bd5cb8f98)

Video (min 1:34 se alcanza a ver):
https://youtu.be/ULdpmyfzsOw?t=94

**Comment by hanswff** [comment]
Hola! Me gustaría colaborar a agregar esto, puede estar interesante.

**Comment by emilianog94** [comment]
Hola @AlejandroJorba , gracias por la sugerencia!

Al menos por el momento me es imposible implementar esto porque el funcionamiento vía SteamDB es utilizando la base de datos de SteamDB, y yo no tengo almacenado en ningún lugar el histórico de mejores ofertas de cada producto :( .

Por otro lado, estoy enfocando esfuerzos en implementar ideas que van más allá de lo que SteamDB hace actualmente (y que por cierto lo hace muuuy bien)

Un saludo!
