### ISSUE TITLE
[FEATURE] Guia de ahorro pagar con MEP Sin impuestos

### ISSUE THREAD

**Issue by iaPedrosa** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#138]
Hola! Primero que nada, muy buena tu app.

Hoy descubri que una forma mas barata de pagar es con MEP sin impuestos, por lo que te queda el precio del juego directamente al valor del MEP.

Yo lo hice pagando con brubank

Configuras asi

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/63590425/dadc1d42-b898-4268-af64-7fb7a455d07e)

Y directamente te resta los dolares que tengas en tu caja de ahorro en dolares. 

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/63590425/3a05359c-9628-43af-b4ee-c7cf5e48a875)

Y no me resto ningun impuesto!

**Comment by emilianog94** [comment]
Hola @iaPedrosa , es muy buena la data que traés! 

Voy a probarla ya que tengo Brubank y de paso averiguar si hay más bancos que lo ofrezcan para ver si lo puedo tirar como un dato en la sección de mejor método de pago.

Un saludo y muchas gracias por compartir!

**Comment by emilianog94** [comment]
Hola @iaPedrosa !

Hice averiguaciones a través de Brubank y me indicaron que de toda manera te cobran los impuestos aún pagando con dólares:
![impuestos brubank](https://github.com/user-attachments/assets/42a43ea0-710e-4528-9a65-01d614a64fc1)


Esto también pude comprobar que lo hace Santander. 

Más allá de que en alguna transacción no te hayan cobrado impuestos, temporalmente preferiría no agregarlo al sitio para evitar que alguien compre y le caiga algún impuesto inesperado de la nada y me termine puteando a mí 😅. 

Gracias de todos modos!
