### ISSUE TITLE
[FEATURE] Countdown

### ISSUE THREAD

**Issue by AlejandroJorba** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#139]
Como andas Emi, se me ocurrió una cosa y justo ahora que está la movida con Press Over quizas podas hacer algo en el home de Steam, la idea principal era un timer colocando la próxima oferta más cercana y quizas que al hacer click te redirija a un calendario donde figuren todas las fechas, ahí entra todo el mambo con Press Over, quizas también puedan organizar con ADVA y otros devs armar algunas ofertas exclusivas para juegos argentinos y colocarlas ahí, inclusive también poner videos de eventos en vivo en el inicio, así como hace steam con las conferencias del "E3".

Otra idea también sería colocar un timer para el próximo lanzamiento de algún juego argentino e inclusive latinoamericano, no los dejemos afuera que hay que apoyar la industria de latam.

Espero que sirva el aporte para al menos darte alguna idea de algo.

**Comment by emilianog94** [comment]
Hola Alejandro, muchísimas gracias por las excelentes sugerencias!

Te confirmo que tengo en mi backlog implementar un Countdown en la extensión para cuando se acercan eventos propios de Steam (ejemplo: Summer Sales, festivales de un género particular, etc). Estoy configurando mi servidor para que esto sea posible de alguna manera en el futuro ya que la extensión debe consultar pedir información a algún lugar. 

Estaría bueno en el futuro ver qué más le puede llegar a interesar al usuario de Steamcito. En un principio, todos los avisos de eventos de industria nacional van a estar en la enciclopedia! 

Noté también que en la sección "Próximos Lanzamientos" de la enciclopedia hay juegos que están hace mucho tiempo sin dar señales y se mezclan con otros cuyo desarrollo está muy activo y su lanzamiento es inminente. Vamos a poner en la Home un feed con cuenta atrás para todos los juegos cuyo lanzamiento esté pautado dentro de los próximos siete días así hay visibilidad.

Un saludo y gracias nuevamente!

**Comment by emilianog94** [comment]
Respecto a los juegos latinoamericanos seguramente es algo que vamos a considerar recopilar!

**Comment by AlejandroJorba** [comment]
Considero por ahí colocar esa info en el inicio de steam, quizas no todos entren regularmente a la enciclopedia y por ahi abren steam, ven el evento y se copan, muy bueno lo que se viene, gracias por la buena onda!

**Comment by emilianog94** [comment]
Gracias Alejandro! Te confirmo que a partir de la próxima semana voy a estar agregando un acceso a la enciclopedia para que la mayoría de los usuarios de la extensión puedan conocerla, te dejo un adelanto de cómo está planteado:

![image](https://github.com/user-attachments/assets/142687f5-573e-436a-b2c8-da24d5e057b1)

**Comment by emilianog94** [comment]
Alejandro, por el momento cierro el issue ya que momentáneamente no voy a avanzar con eso para no interferir en la navegación del usuario en la tienda de Steam y que se vuelva algo invasivo.  

Muchas gracias!!
