### ISSUE TITLE
[BUG] Precio sin impuestos en tienda de juego

### ISSUE THREAD

**Issue by FrancoRav** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#14]
**Describí el bug**
Los precios en la tienda (itemstore) de un juego no aparecen con impuestos hasta entrar al item específico

**¿Qué pasos seguiste para llegar al bug?**
1. Abrir [la tienda de un juego](https://store.steampowered.com/itemstore/365960/) (tienda de rFactor 2, los precios se ven sin impuestos)
2. Entrar a cualquiera de los items ([este](https://store.steampowered.com/itemstore/365960/detail/36/) por ejemplo), ahí se ve el precio con impuestos

**Capturas de Pantalla**
[Album de Imgur](https://imgur.com/a/w8kHKc6)

**Información de tu PC**
 - Navegador que estás usando: Brave
 - Versión de la extensión: 0.60

**Comentarios adicionales**
No es algo importante, pero hago el report por si no lo habías visto y lo querés solucionar

**Comment by emilianog94** [comment]
Hola Franco, gracias por el reporte. 

Se va a trabajar para que Steamcito sea compatible con las itemstores de los juegos. En la próxima release se va a incluir esta funcionalidad.

¡Saludos!

**Comment by emilianog94** [comment]
Hola Franco, la funcionalidad fue añadida en la v0.62 que está programada para lanzarse mañana 04/01/2021 en Chrome Store y Mozilla Addons. 

Preview de la funcionalidad:
![image](https://user-images.githubusercontent.com/38828911/103493031-be595900-4e0d-11eb-9b92-5fbaa03748c3.png)


Podés ver los detalles de la actualización en https://emilianog94.github.io/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/landing/changelog.html

¡saludos!

**Comment by emilianog94** [comment]
La nueva versión ya está disponible en Chrome Store y Mozilla Addons, cierro el issue!
