### ISSUE TITLE
[BUG] La nueva categoría empuja los elementos de menú

### ISSUE THREAD

**Issue by LeyendaV** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#141]
**Describí el bug**
El menú de Steam no estaba pensado para agregar otro elemento, menos uno tan ancho. De momento esconde el espacio libre restante y el ~90% de la categoría Laboratorios. Si Valve llegara a sumar otro elemento, sería totalmente inaccesible.

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Simplemente ingresar a https://store.steampowered.com/ y ya es visible.

**Capturas de Pantalla**
![image](https://github.com/user-attachments/assets/f643eb07-e477-4361-afde-b4cc79574036)
![image](https://github.com/user-attachments/assets/13fc6873-2537-47cb-9abe-eb0befec744f)

**Información de tu PC**
 - Navegador que estás usando: Edge 126.0.2592.102 (Compilación oficial) (64 bits)
 - Versión de la extensión: 3.60

**Comentarios adicionales**
Agregar un scroll lateral dentro del menú solucionaría el inconveniente. Caso contrario, puede ser una alternativa dejar solamente la bandera y eliminar el texto.

**Comment by emilianog94** [comment]
Hola @LeyendaV , gracias por notarlo! 

Te soy sincero: escogí el mal menor que es que el último elemento de Laboratorio aparezca cortado 😆. Planeo hacer un hotfix en la próxima versión para que sea posible scrollear por la barra así no parece que hay algo cortado. 

Un saludo!

**Comment by emilianog94** [comment]
Nunca cerré este issue! 😅
