### ISSUE TITLE
[BUG] Visualización de Emojis retrocompatibles en Steamcito Cart

### ISSUE THREAD

**Issue by serialito74** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#144]
**Describí el bug**
Al ir a shopping cart, se presenta un problema en steamcito_cart_wallet_value y  steamcito_cart_currentmethod_value

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. [Steam Cart](https://store.steampowered.com/cart)

**Capturas de Pantalla**
![image](https://github.com/user-attachments/assets/2a29ba1c-9a2e-4766-bc3d-5a7bce3c383f)

**Información de tu PC**
 - Navegador que estás usando:  Brave  1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit) 
 - Versión de la extensión: 3.61

**Comentarios adicionales**

**Comment by JackER4565** [comment]
hola me baje el navegador y no pude replicar el bug:

![image](https://github.com/user-attachments/assets/0223b7d9-9aec-428d-842e-60c72c9cde29)


capaz otra extension molestando?...

**Comment by emilianog94** [comment]
Hola @serialito74 !
Recién puedo ver esto. 

La captura de pantalla que estás mostrando entiendo que pertenece a la versión 3.60 , ya que en la versión 3.61 se removió la visualización de emojis en esa sección cuando usás emojis retrocompatibles. 

Te adjunto una captura de pantalla que saqué actualmente usando Brave: 

![image](https://github.com/user-attachments/assets/8f623210-3e60-4e58-98de-d5492b4a8f70)


¿Me confirmás si efectivamente te está funcionando bien al día de hoy? Un saludo y perdón la demora.

**Comment by serialito74** [comment]
Hola! que raro, acabo de probar nuevamente y continuo con el error
![image](https://github.com/user-attachments/assets/e7fd3781-ffaf-473e-be4a-c5ff73dc5a21)

steamcito version
![image](https://github.com/user-attachments/assets/94fb03ce-3ae8-4375-8e0c-f7ddae199955)

**Comment by serialito74** [comment]
tenes toda la razon, eso me pasa por no limpiar el local store.. algo habia quedado cacheado, luego de limpiar el local store funciona perfecto!
![image](https://github.com/user-attachments/assets/f221a223-37e8-4a53-92d3-aec474149f2f)
