### ISSUE TITLE
[FEATURE] Abrir el changelog en una nueva pestaña/tab

### ISSUE THREAD

**Issue by Squaredude** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#146]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Cuando hay un mensaje de Steamcito sobre una nueva actualización, haciendo click en el link del mensaje que aparece en la página principal de Steam, te manda al changelog en la página de Steamcito en la misma pestaña.

**¿Qué te gustaría que ocurra?**
Opino que se debe abrir una nueva pestaña.

**Alternativas que hayas considerado**
Hacer click con la ruedita del mouse, pero a veces me olvido. 😅

**Comentarios Adicionales**
Es una pavada, pero me pasa con cada actualización. Jajajaja!

**Comment by JackER4565** [comment]
Es raro por que en el helpers.js esta como target en "_blank", que te deberia abrir una pestaña nueva:

`
                        <a href="${changelogUrl}" target="_blank">¿Qué hay de nuevo?</a>
                  `

**Comment by Squaredude** [comment]
Ahhh, bueno. Puede ser que sea el navegador, entonces. Justo volví a pasarme de Firefox a Vivaldi, y en una de esas algo estaba mal configurado. Disculpas!

**Comment by emilianog94** [comment]
Buenas!

Tal como comentó @JackER4565 , esto no debería ser un problema porque el parámetro _blank está definido. 

Recién acabo de forzar una actualización local manualmente simplemente para chequear en Chromium y funciona perfecto! 
![image](https://github.com/user-attachments/assets/ebb39f4a-32c4-4291-942a-1ee39d3b5a83)

Debería estar abriendo siempre por default en pestaña nueva sin necesidad de tocar ruedita del mouse. 
¿Me avisás en una futura actualización si ocurre? Temporalmente cierro el issue!
