### ISSUE TITLE
[BUG] el emoticon de dolar crypto es un cuadrado 🪙

### ISSUE THREAD

**Issue by JackER4565** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#147]
**Describí el bug**
el dolar crypto no tiene un emoticon como el resto, 

**¿Qué pasos seguiste para llegar al bug?**
1. Entrar al menu de steamcito
2. Abrir dropdown metodo de pago
3. Apareció el error

**Capturas de Pantalla**
![image](https://github.com/user-attachments/assets/d496f82f-5270-4ae3-a8ac-8aa525c1f5a1)

**Comentarios adicionales**
capaz se puede usar este: ₿ o este 🥮 o la bolsa 💰

**Comment by Squaredude** [comment]
Pasa lo mismo cuando usás los emojis "retrocompatibles"? (La segunda opción en la sección "Opciones visuales")

Podés ver este emoji? >>> 🪙

Por lo menos yo puedo verlo correctamente en Steamcito 3.61, tanto en Firefox como en Vivaldi. Estoy usando la fuente Noto en Linux.

**Comment by JackER4565** [comment]
> Pasa lo mismo cuando usás los emojis "retrocompatibles"? (La segunda opción en la sección "Opciones visuales")
> 
> Podés ver este emoji? >>> 🪙
> 
> Por lo menos yo puedo verlo correctamente en Steamcito 3.61, tanto en Firefox como en Vivaldi. Estoy usando la fuente Noto en Linux.

Ahí probe y en ambos modos veo el cuadrado, acá también, ese que mostras lo veo como un cuadrado.

**Comment by Squaredude** [comment]
Habría que ver cuál fuente es la que estás usando, ya que los emojis dependen de eso. Hay fuentes que no están actualizadas. Por ejemplo, en Windows 10 recuerdo que la fuente había quedado desactualizada y no incluía los nuevos emojis (y creo que el emoji de la moneda justo no está en la versión de la fuente Segoe UI Emoji que usa Win10).

Fijate si podés bajar la fuente Noto Color Emoji (de Google), que está más actualizada: https://github.com/googlefonts/noto-emoji

**Comment by Squaredude** [comment]
Mala mía, con el link anterior.

Acá sería el verdadero link para bajar: https://fonts.google.com/noto/specimen/Noto+Color+Emoji

Es medio confuso, pero tenés que agregar la fuente a una especie de carrito y después la bajás.

![image](https://github.com/user-attachments/assets/006c09e7-cd9b-4911-bb3e-94da1c604ccd)
(Hacer click en "Get font")

![image](https://github.com/user-attachments/assets/e0147a13-6e9b-40cb-bf83-afc6935cf072)
(Hacer click en el ícono de descarga, abajo de "Remove all")

Ahí se descarga un archivo ZIP, adentro está la fuente. Parece más grande de la que bajé del Github, así que debe ser mejor. 🤷🏻‍♂️ Si mal no recuerdo, en el Explorador de Windows, solamente necesitás hacer doble click, o click derecho e "Instalar...".

**Comment by emilianog94** [comment]
Hola @JackER4565 !

Tal como comentó @Squaredude esto se debe a que la versión de Windows 10 es muy vieja y la fuente predeterminada no tiene compatibilidad con algunos emojis como el de la moneda. 

@Squaredude , creo que es una excelente idea hacer embed de la font en la extensión, esto es posible. Sin embargo hay un problema: la fuente de Noto Color Emoji es pesadísima, 24mbs para usar solamente tres emojis. 

Voy a ver si existe alguna forma de desempaquetar la fuente y recompilarla solamente con los tres emojis necesarios así la subo a la extensión y la tomo por default. Estaría genial que se pueda hacer , lo voy a investigar y probar en una compu con W10! 

Muchas gracias, dejo el issue abierto para novedades!

**Comment by emilianog94** [comment]
Je, acabo de pasar como 2hs usando software para decompilar y recompilar fonts (sin éxito porque al ser una font unicode no mantiene estilos ni colores) 

Ya pude encontrarle la vuelta, era mucho más fácil! 
Google Fonts permite hacer subsetting (tomar sólamente los caracteres que necesitás) directamente desde su CDN.

Ejemplo: https://fonts.googleapis.com/css2?family=Noto+Color+Emoji&text=%F0%9F%AA%99%F0%9F%A7%89%F0%9F%92%B2

Con hacer embed del kit provisto por Google Fonts anda perfecto y pesa solamente 3kbs

@JackER4565 esta semana lo estoy comitteando al repo!
![image](https://github.com/user-attachments/assets/2c98302b-c6b6-402d-b6ec-51b9303d8d2b)

**Comment by emilianog94** [comment]
Buenas @JackER4565 , podrás probar si te funciona correctamente ahora? 

Podés descargar la nueva versión desde la branch feature/noto-emojis
https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/tree/feature/noto-emojis

**Comment by Squaredude** [comment]
No soy jack 😜, pero te comento que justo tengo una VM con Windows 10 así que decidí probar.

Pareciera que funciona. Comparé con la versión 3.61 y pude ver el cuadrado con esa versión, como era de esperarse.

Con el branch noto-emojis, la moneda aparece correctamente.

Lo único que noté es que en el menú donde se selecciona el método de pago, no aparecen los emojis:

![Screenshot 2024-09-14 203004](https://github.com/user-attachments/assets/d705f880-ba4a-45b1-a919-850c058e1988)

No sé si decidiste sacarlos de ahí o es un bug.

**Comment by emilianog94** [comment]
Gracias por confirmar @Squaredude !

Quité los emojis del selector porque en HTML no podés poner múltiples selectores HTML adentro de un tag "option", es decir no es posible mezclar dos fonts distintas.

**Comment by Squaredude** [comment]
Ahhh, bien!

Y se podría poner el emoji al lado del drop-down después de seleccionar la opción?

**Comment by emilianog94** [comment]
Buenas @Squaredude ! 

Encontré una forma más sencilla de solucionarlo. 

¿Podrías descargar nuevamente la versión de la branch https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/tree/feature/noto-emojis y probarlo nuevamente en la VM con Windows 10 y confirmarme si ves bien el emoji en el selector de método de pago? Muchas gracias

**Comment by JackER4565** [comment]
buenas! disculpen el cuelgue!!!
baje recien recien la versión de la rama "noto-emojis" y aparece con el cuadrado aun:
![image](https://github.com/user-attachments/assets/de688997-a6c6-4b30-9b32-6267513cebcb)

**Comment by emilianog94** [comment]
> buenas! disculpen el cuelgue!!! baje recien recien la versión de la rama "noto-emojis" y aparece con el cuadrado aun: ![image](https://private-user-images.githubusercontent.com/94895169/367805240-de688997-a6c6-4b30-9b32-6267513cebcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTg1NzYsIm5iZiI6MTcyNjQ5ODI3NiwicGF0aCI6Ii85NDg5NTE2OS8zNjc4MDUyNDAtZGU2ODg5OTctYTZjNi00YjMwLTliMzItNjI2NzUxM2NlYmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE0NTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Mjc5MTRlY2MyNDA5Y2NmYTZkYjUzYjkyYjFkNDljMWY2MWQ0NTVlOTdkNDBmYjhhZDdlNjY0N2NlNjkwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMCYb_s2u-rVGWdJMnBdmHar-hLLOEarbzeMbir2ups)

Buenas @JackER4565 ! No hay drama. 
Creo que la descargaste pero no la activaste, porque la versión es 3.70. 

El proceso es el siguiente: 

1. Descargar el zip
2. Descomprimir la carpeta chrome_extension
3. Abrir la central de extensiones de Chrome y arriba a la derecha activar la casilla "Modo Desarrollador"
4. Arriba a la izquierda clickear en "Carga Descomprimida"
5. Buscar el directorio recién descomprimido y seleccionarlo
6. Listo, se te va a activar la versión local

![image](https://github.com/user-attachments/assets/caeeefa0-08d8-4a6f-9306-934e151d0c4c)

**Comment by JackER4565** [comment]
ahora si, no cambie la rama cuando lo cloné jaja
![image](https://github.com/user-attachments/assets/ded440a4-f886-4581-b0ea-adf2b9875c9d)

**Comment by Squaredude** [comment]
Confirmo también que funcionó en la VM. Justo tuve un problema con Guest Additions y no podía pasar la captura de pantalla. 😅

![image](https://github.com/user-attachments/assets/39ea79fc-f3f1-4b78-9eb0-a36415f4fb48)

**Comment by emilianog94** [comment]
Genial muchas gracias a ambos @Squaredude  @JackER4565 ! 

En el transcurso de esta semana (apenas termine de adaptar todo a Firefox), voy a lanzar la v3.70 en conjunto con varios enhancements y fixes más!

**Comment by emilianog94** [comment]
Listo en v3.70! Muchas gracias!
https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/releases/tag/v3.70

Cierro el issue
