### ISSUE TITLE
Bitrefill toma el precio bitcoin, no USDC

### ISSUE THREAD

**Issue by pekynes** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#148]
Buenas, el problema es el siguiente:

La aplicacion por la cual se compran los USD para la steam wallet, toma el precio de Bitcoin, no de USDC, por lo tanto se paga un precio diferente al cual aparece en la pagina de steam con la extension Steamcito.

Saludos!.

**Comment by emilianog94** [comment]
Buenas @pekynes !

La extensión del navegador toma una cotización del dólar Crypto provista por Ámbito Financiero y suele ser la más fiable, es la que se usa de referencia en la mayoría de los portales económicos: https://www.ambito.com/dolar-cripto

Actualmente el exchanger que mencionás, Belo, tiene su propia cotización que es marginalmente más cara y se puede ver desde acá: https://steamcito.com.ar/mejor-metodo-de-pago-steam-argentina

Por el momento no se encuentra en mis planes utilizar la cotización de Belo en la extensión ya que el valor provisto por Ámbito Financiero es mucho más representativo del ecosistema de exchangers crypto de Argentina. Tal vez en el futuro pueda hacer que sea posible elegir la de Belo desde la extensión, pero por el momento desde un apartado puramente técnico (no tengo permisos para traer la cotización de Belo desde el frontend hacia la extensión) no me es posible!
