### ISSUE TITLE
[BUG] La extensión dejó de funcionar en la wishlist

### ISSUE THREAD

**Issue by emilianosalcedo** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#155]
**Describí el bug**
Recientemente la extensión dejó de mostrar los precios de Argentina en la wishlist

**¿Qué pasos seguiste para llegar al bug?**
URL: https://store.steampowered.com/wishlist/id/USER/?sort=discount

**Capturas de Pantalla**
Como se ve no aparece el ícono de steamcito al lado del user ni se ven los precios en la lista
![image](https://github.com/user-attachments/assets/f0987827-3d7c-4a82-a654-45b513559bc9)

**Información de tu PC**
 - Navegador que estás usando: Google Chrome
 - Versión de la extensión: 3.72

**Comentarios adicionales**
En la única sección del sitio donde no se aplica la extensión es en la wishlist, en todo el resto funciona correctamente.

**Comment by emilianog94** [comment]
Hola @emilianosalcedo , muchas gracias por tu reporte! 

Según estuve viendo, en algún momento de la última semana Steam migró el frontend de la Wishlist a React y esto modificó mucho su estructura. Por esa razón la extensión ya no detecta los contenedores de precios en las wishlist.

Voy a adaptar la extensión para detectar correctamente los contenedores de precios nuevamente.

Un saludo y gracias!

**Comment by emilianosalcedo** [comment]
Tenes razon, esta usando React para renderizar.

Muchas gracias! Te felicito por el trabajo que le diste a la extension!

Saludos!

**Comment by emilianog94** [comment]
Actualizo status: el bug está solucionado en https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/tree/feature/v380 y la actualización será lanzada en el transcurso de esta semana!

![image](https://github.com/user-attachments/assets/3eab285b-8cf6-42c4-89e8-5305f94c4696)

**Comment by emilianosalcedo** [comment]
Perfecto! Gracias!

**Comment by emilianog94** [comment]
Hola @emilianosalcedo , hoy al mediodía envié la actualización a Chrome Web Store así que imagino que en el transcurso de hoy y mañana llegará la V3.80 a todos los navegadores.
Va el changelog acá: https://steamcito.com.ar/changelog

 Cualquier cosa me avisás. 

Un saludo y muchas gracias desde ya!

**Comment by emilianog94** [comment]
Hola @redeven !

Ya tengo listo el fix para Firefox, pero tardan hasta una semana en aprobármelo.
https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/pull/157

Como suelen tardar en aprobarlo y tengo que lanzar una nueva actualización la próxima semana por la quita del impuesto PAIS del 22 de Diciembre, estoy trabajando en una actualización para que los impuestos vigentes de cada método de pago sean obtenidos dinámicamente en vez de que estén hardcodeados en la extensión como ocurre actualmente. 

Apenas tenga lista esa actualización lanzo todo junto para Chrome y Firefox!
