### ISSUE TITLE
[BUG] Devolución de percepciones no aparece para 2025

### ISSUE THREAD

**Issue by lucasSaavedra123** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#160]
**Describí el bug**
Quise ver cuanto me pueden devolver en percepciones en el 2025 y me aparece $0.

**¿Qué pasos seguiste para llegar al bug?**
1. Fui al historial de transacciones de Steam.

**Información de tu PC**
 - Navegador que estás usando: Brave.
 - Versión de la extensión: 3.90

**Comentarios adicionales**
Tal vez es por algun cambio regulatorio que yo desconozca.

**Comment by emilianog94** [comment]
Buenas @lucasSaavedra123 , gracias por tu aviso! 

Lamentablemente la sección de Historial de compras + Cálculo de devolución es problemática desde que se dolarizó la tienda de Steam en Noviembre de 2023.

Tras la dolarización, el precio de los juegos pasó a depender de la cotización del dólar de cada día, y lamentablemente Steamcito no lleva registro histórico de la cotización del dólar de cada día del año. Como solamente toma la cotización del dólar del día de hoy, el cálculo de devolución anual de las compras sería impreciso y poco útil.

Muy posiblemente voy a eliminar la funcionalidad de la sección Historial para evitar confusiones, ya lo quité del sitio web. 
Un saludo y gracias!
