### ISSUE TITLE
MercadoPago cobra 65% en vez de 64% - Ajustar importe (03/Marzo/2021)

### ISSUE THREAD

**Issue by luCh0j** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#17]
Impuestos = 165% (Argentina) 🇦🇷

$100 = $165
$400 = $660

$800 = $1320

$1600 = $2640
$3200 = $5280

**Comment by emilianog94** [comment]
Hola @luCh0j ! Gracias por el reporte. 

Estoy al tanto que desde inicios de Febrero MercadoPago comenzó a cobrar un monto superior. Anteriormente cobraba 58.18%, y ahora pasó a cobrar un **65%** tal como indicás. 

A nivel oficial, los impuestos nacionales son de un **64%**. Para poder solucionar estas pequeñas variaciones que existen entre diferentes emisores de tarjetas muy pronto lanzaré una actualización que va a permitir elegir dos opciones: 

- **Opción A**: Utilizar Steamcito con los impuestos oficiales que figuran en la web de AFIP (Recomendado)
- **Opción B**: Utilizar Steamcito con impuestos personalizados. Esto te va a permitir definir de forma manual el porcentaje de impuestos, ideal para casos particulares como MercadoPago que cobra un monto superior, o el caso de Tierra del Fuego que no paga IVA, entre otros.

Dejo el issue abierto para informar de la actualización. ¡Saludos y gracias!

**Comment by emilianog94** [comment]
Hola @luCh0j , la funcionalidad ya se encuentra programada y se encuentra en proceso de testeo, en los próximos días estará disponible! 

Adjunto captura de pantalla de funcionalidad:
![image](https://user-images.githubusercontent.com/38828911/110730824-e7c4a580-81ff-11eb-8dd2-f40a1b5cb18d.png)

**Comment by emilianog94** [comment]
Hola@luCh0j , la nueva versión ya fue lanzada y aprobada en todas las stores. Cualquier consulta podés avisar. 

¡saludos y gracias!
