### ISSUE TITLE
[BUG] Historial de compras muestra como si los impuestos estuvieron siempre

### ISSUE THREAD

**Issue by fkandus** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#20]
**Describí el bug**
El historial de compras está considerando como si el impuesto solidario y la retención de ganancias hubiesen estado desde siempre. Por ejemplo en compras de 2018.

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí esta URL https://store.steampowered.com/account/history/ (es propia del usuario loggeado)
2. Fui a las compras más viejas que tengo registradas
3. Por ejemplo, en compras de 2018 se calcula el precio con los impuestos actuales.

**Información de tu PC**
 - Navegador que estás usando: Brave 1.22.71
 - Versión de la extensión: 0.8

**Comment by emilianog94** [comment]
Hola Federico! 

Muy buena observación, realmente no lo había considerado. Actualmente Steamcito toma un valor impositivo único (este puede ser el default de Steamcito o bien uno personalizado). 

Voy a tener en cuenta la posibilidad de implementar un registro histórico de las modificaciones en los impuestos. Esto podría servir tanto para ver el historial de una forma más precisa como para también visualizar gráficamente la evolución de los impuestos en algúna sección de interés. 

Dejo el issue abierto para futuras actualizaciones. Un saludo y gracias!

**Comment by pyoneerC** [comment]
Esto esta resuelto? Si es asi, cerrar issue 😄

**Comment by emilianog94** [comment]
![](https://media.giphy.com/media/FoH28ucxZFJZu/giphy.gif)

Tarde pero llegó! 
La versión v3.30 cuenta con el histórico de impuestos para el historial :) 

https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/releases/tag/v3.30
