### ISSUE TITLE
[BUG] Problema mostrando precios de microtransacciones 

### ISSUE THREAD

**Issue by mcg-git** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#21]
![image](https://user-images.githubusercontent.com/66498963/116004972-7425fe80-a5db-11eb-8448-42b23477cf21.png)
No me aparecen los precios, tal como se ve en la foto. El emoji del mate no es clickeable. Cuando desactivo la extensión aparecen (sin impuestos)

**Comment by mcg-git** [comment]
ahora lo hago de nuevo con la plantilla

**Comment by emilianog94** [comment]
Hola @mcg-git ! 

Te agradezco por tu reporte. No es necesario que lo hagas con la plantilla, entiendo que estás queriendo ver los precios de una microtransacción ingame.

Ya pude replicar el error, efectivamente tras la actualización v0.80 no se testeó debidamente esta funcionalidad. ¡Va a estar solucionada esta misma semana!

Un saludo.

**Comment by emilianog94** [comment]
Hola @mcg-git , te confirmo que esto fue solucionado en el lanzamiento de la versión 1.0 de Steamcito del día de hoy, se actualizará en las próximas horas en tu navegador de preferencia. 

Cualquier duda podés avisar. ¡un saludo y gracias por tu reporte!
