### ISSUE TITLE
[FEATURE] Precios de Steamcito en los mails de Steam

### ISSUE THREAD

**Issue by sqrg** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#23]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Los precios en los mails de Steam siguen teniendo los valores originales

**¿Qué te gustaría que ocurra?**
Aplicar en los clientes de correo los mismos cambios que en la web para mostrar los impuestos

**Comment by emilianog94** [comment]
Buenas Santiago, como estás? 

También recibo mails cuando un juego de mi Wishlist se encuentra en oferta y estaría bueno ver el precio final ahí también. 

Lamentablemente esto no es posible hacerlo porque los mails se encuentran fuera del alcance de los permisos de Steamcito.
Actualmente Steamcito tiene permisos para interpretar el DOM en los siguientes dominios:
- https://store.steampowered.com/ 
- https://steamcommunity.com/ 

Para lograr esta nueva funcionalidad, Steamcito debería requerir nuevos permisos a las URL de la mayoría de los clientes de mail más utilizados (gmail.com, outlook.com, yahoo.com). Requerir más permisos que los iniciales no es una buena práctica, y por eso Chrome (y la mayoría de los navegadores) **desactivan la extensión para todos los usuarios y los obliga a instalarla nuevamente para aceptar los permisos**, lo cual sería algo muy molesto!

Por esta razón es que todo lo que esté fuera de la tienda de los dominios de Steam no puede ser accedido por Steamcito. 

Desde ya te agradezco por acercar la sugerencia. ¡un saludo!

**Comment by sqrg** [comment]
Tiene sentido. Gracias por la respuesta!
