### ISSUE TITLE
[BUG] No todos los productos tienen la conversion de precio hecha

### ISSUE THREAD

**Issue by matiasalek** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#24]
**Describí el bug**
Cuando entro a la pagina principal de Steam o mi wishlist, no todos los juegos tienen el icono del matecito, algunos tienen el signo de pesos (es decir el precio sin impuestos) y otros tienen matecito, se soluciona simplemente haciendo clic en el signo de dolar para transformarlo a matecito, pero no se que criterio aplica y por que algunos me los muestra con impuestos y otros no, hasta hace unos dias funcionaba bien y ahora depende del producto que quiera ver.

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Entrar a la pagina principal de Steam o bien a la wishlist
2. Comparar precios de distintos productos
3. Ver la diferencia de iconos y precios.

**Capturas de Pantalla**
![Screenshot 2021-06-20 at 19-45-15 Venganzz's wishlist](https://user-images.githubusercontent.com/31048494/122690458-0fb0a580-d200-11eb-80da-370bfc56fe71.png)

**Información de tu PC**
 - Navegador que estás usando: Firefox 89.0.1
 - Versión de la extensión: 1.0

**Comment by emilianog94** [comment]
Buenas @matiasalek ! Acabo de revisar tu reporte. Entiendo que estás entrando a la tienda de Steam logueado.

Esto que estás viendo es una feature de Steamcito que se activa cuando tenés cargado saldo de Steam Wallet en tu cuenta. 
Steamcito lee el total de tu saldo en la parte superior derecha del navegador y en base a eso te muestra el precio de todos aquellos juegos que podés comprar sin impuesto. **El signo $ significa que podés comprarlo con la totalidad de tu saldo sin impuesto alguno!** 

Por ejemplo, en esta captura tengo $54,80 de saldo cargado, y un juego de $53,99 se me ve con signo $.
![image](https://user-images.githubusercontent.com/38828911/122692059-6078cc00-d209-11eb-8293-5335b857b56f.png)

Imagino que tu en tu caso se ven de esa manera porque tenés más de $80,99 cargados a tu wallet, ¿es eso? 

Un saludo.

**Comment by matiasalek** [comment]
Exacto era eso, no me di cuenta. Antes no tenia saldo en la wallet y ahora si, disculpa, no me di cuenta de eso.

Gracias por responder rapido y gracias por la extension que creaste que es tremendamente util.

Saludos!
