### ISSUE TITLE
[BUG] Día incorrecto en la página web

### ISSUE THREAD

**Issue by maromalo** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#25]
**Describí el bug**
En la página web (https://steamcito.com.ar/), la fecha de "hoy" no es la misma que la fecha en Argentina y la de mi PC. 

**Capturas de Pantalla**
![Mauro_210620-220654](https://user-images.githubusercontent.com/54760464/122696448-71313e00-d219-11eb-83b1-a9521dde976c.png)

**Información de tu PC**
 - Navegador que estás usando: Brave y Edge

**Comentarios adicionales** 
Este error no es para nada importante (no afecta a la extensión ni mucho a la página web), pero como la extensión está hecha principalmente para usuarios argentinos, siento que la fecha debería estar acorde (o usar la fecha de las PC clientes)

**Comment by emilianog94** [comment]
Buenas @maromalo , gracias por notar el detalle! 

Comprobé que el desfasaje horario se debe a que el servidor está un poco adelantado porque tiene la hora de Estados Unidos. Apenas termine el lanzamiento de la nueva versión esta semana lo corrijo.

¡un saludo!

**Comment by emilianog94** [comment]
Solucionado @maromalo , gracias!
