### ISSUE TITLE
[FEATURE] Precios de Steamcito en SteamDB.info

### ISSUE THREAD

**Issue by pscrespo** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#27]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
El sitio Steamdb.info es un sitio que utiliza SteamKit para mostrar información detallada del historial de precios de productos de Steam, incluyendo promociones, precios mácimos y mínimos, etc. Incluso tiene un link en el final de cada página para realizar la compra en Steam de lo que estamos viendo.
**¿Qué te gustaría que ocurra?**
Si es posible, extender el uso de Steamcito al sitio de SteamDB, para que la representación de los precios, y el link del final hacia Steam, reflejen los precios acutales con los impuestos incluidos.

**Comment by emilianog94** [comment]
Buenas @pscrespo !

Es una muy buena idea, yo también utilizo SteamDB para ver el historial y variaciones de precios de los juegos. Lamentablemente esto no es posible actualmente (al menos desde la extensión de Steamcito) porque SteamDB.info o cualquier otro dominio están fuera del alcance de los permisos de Steamcito. Steamcito tiene permisos para leer los siguientes dominios:
https://store.steampowered.com/
https://steamcommunity.com/


Para lograr esta nueva funcionalidad, se deberían requerir nuevos permisos de URL, y como esto no es una buena práctica, Chrome y la mayoría de los navegadores desactivan la extensión para todos los usuarios y los insta a reinstalarla manualmentepara aceptar los permisos, dejando la extensión en cero usuarios.

Por esta razón es que todo lo que esté fuera de la tienda de los dominios de Steam no puede ser accedido por Steamcito lamentablemente! Desde ya te agradezco por la sugerencia de todos modos. ¡un saludo!
