### ISSUE TITLE
[FEATURE] un total del precio por default.

### ISSUE THREAD

**Issue by limonetas** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#28]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Descripción del problema. Ejemplo: "es medio frustrante que..."

Bueno, ya que me molesta un poco por no tener en default los precios de steam en ves que veo de primera con el total de impuestos.

**¿Qué te gustaría que ocurra?**
Descripción corta y concisa acerca de cuál pensás que es la solución.

Lo que dice mi titulo y la imagen xd

**Alternativas que hayas considerado**
Una o más alternativas que se te hayan ocurrido para solucionar el problema

Ay no se

**Comentarios Adicionales**
Capturas de pantalla o más información sobre tu sugerencia

![adasdsd](https://user-images.githubusercontent.com/47794002/132934528-63b4eaf0-1093-4c5a-ad09-039a3d7973a1.png)

**Comment by emilianog94** [comment]
Buenas @limonetas ! Recién veo esto, te agradezco por la sugerencia. Estaría bueno poder ver el precio del total del carrito sin los impuestos incluidos tal como indicás. 

Voy a evaluar cómo es la mejor manera de implementarlo en la próxima versión de Steamcito!

**Comment by Squaredude** [comment]
Venía a sugerir esto.

Estaría bueno que apareciera antes de "Total Final pagando con Tarjeta".

**Comment by emilianog94** [comment]
Hola @limonetas !

Algo tarde, sin embargo en esta nueva versión de Steamcito v1.40 se acaba de agregar la funcionalidad para setear el comportamiento default de Steamcito a lo largo de toda la tienda:
https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/releases/tag/v1.40

Saludos!
