### ISSUE TITLE
Error ortográfico en https://steamcito.com.ar/impuestos-hoy

### ISSUE THREAD

**Issue by ramiro2114** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#29]
En https://steamcito.com.ar/impuestos-hoy en el pop up de ¿Por qué existe esta diferencia del 1%?
![image](https://user-images.githubusercontent.com/1613097/138979696-41f767bb-a8f7-419a-9c63-f5d322d474b7.png)
En la parte de abajo pone Recomendiendo.
![image](https://user-images.githubusercontent.com/1613097/138979777-127bb3da-eeff-4202-8664-c5b04b5a60bf.png)
en mi opinión, que no soy estudiante de lengua ni mucho menos, tendría que ir, por ejemplo.
1. Por eso **recomiendo** calcular siempre 65% para que sobre antes que falte.
2. **Recomendando** calcular siempre 65% para que sobre antes que falte. (no sé qué tan bien este está lingüísticamente).

**Comment by emilianog94** [comment]
Buenas @ramiro2114 , gracias por notar el typo, muy pronto lo estoy solucionando!

**Comment by emilianog94** [comment]
Corregido! https://steamcito.com.ar/impuestos-hoy 

@JoseLuisKoller , gracias, no aparece porque el el sitio web se encuentra en un hosting que tiene un repo privado aparte!
