### ISSUE TITLE
[FEATURE] Integracion con steamdb.info

### ISSUE THREAD

**Issue by axcoro** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#30]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Cada vez que hay un ofertas, suelo chusmear en steamdb.info, el tema es que el precio se muestra sin los impuestos

**¿Qué te gustaría que ocurra?**
Misma funcionalidad que dentro de https://store.steampowered.com/

Nice to Have: opción de mostrar el precio original en USD (mouse hover?), ya que muchas veces los precios regionales lo hacen mas tentador el precio

**Alternativas que hayas considerado**
Ninguna

**Comentarios Adicionales**

Si ingresamos a https://steamdb.info/sales/

Vemos lo siguente

![image](https://user-images.githubusercontent.com/5459655/139303776-24b3d255-8bcd-44f7-829f-0bc346b10c25.png)

pero si ingreso al store:

![image](https://user-images.githubusercontent.com/5459655/139304196-598e4da9-57b2-4fe6-bc46-9e8d1e4ba1eb.png)

**Comment by emilianog94** [comment]
Buenas @axcoro !Te agradezco por la sugerencia, sin embargo con la extensión actual en la Chrome Web Store esto no es posible :(  

Te dejo acá un issue con la explicación: https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/issues/23
