### ISSUE TITLE
[BUG] word wrap en la pagina de desarrollador/publisher

### ISSUE THREAD

**Issue by ImUrX** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#31]
**Describí el bug**
![imagen del word wrap](https://i.imgur.com/c23CSrO.png)

**¿Qué pasos seguiste para llegar al bug?**
1. Abrir una pagina de desarrollador, ej https://store.steampowered.com/developer/dinopoloclub
2. profit?

**Información de tu PC**
 - Navegador que estás usando: Firefox 94.0
 - Versión de la extensión: 1.10

**Comment by emilianog94** [comment]
Buenas @ImUrX , gracias por notarlo! Efectivamente en la versión 94 habrán cambiado algún estándar de CSS y se rompió. (tenía la 90 y no podía replicarlo). 

Muy pronto voy a estar solucionándolo!
