### ISSUE TITLE
[BUG] La extensión no calcula los precios de suscripciones

### ISSUE THREAD

**Issue by Fenthral** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#32]
**Describí el bug**
En los menús que se despliegan al hacer click  para elegir opciones de compra los precios no figuran con impuestos

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí esta URL http://store.steampowered.com/app/1286830/STAR_WARS_The_Old_Republic/
2. Ir al menú de suscripción o de compra de moneda del juego
3. Apareció el error

**Capturas de Pantalla**
De ser necesario, agregá capturas del problema
![Sin título](https://user-images.githubusercontent.com/87309388/143662949-e395bc30-eecb-45d1-b4a2-ee70e1a278cd.png)
![Sin título2](https://user-images.githubusercontent.com/87309388/143662958-6aab5c7d-9d66-47c9-8488-e569cc003644.png)

**Información de tu PC**
 - Navegador que estás usando: Chrome 
 - Versión de la extensión: v1.10

**Comentarios adicionales**
Cualquier otro comentario que creas relevante para entender mejor el problema.

**Comment by emilianog94** [comment]
Buenas @Fenthral ! Desde ya te agradezco por el reporte. 

Recién intenté replicarlo en la última versión de Chrome bajo Windows 10 y no me aparece de esa forma: 
![image](https://user-images.githubusercontent.com/38828911/143800092-306713ef-2b73-4fcc-a9a5-e6d53ac8094d.png)

¿Podrías ingresar al link del Old Republic nuevamente https://store.steampowered.com/app/1286830/STAR_WARS_The_Old_Republic/ y tocar **CTRL+SHIFT+J** para desplegar la consola de Chrome y pasarme captura de pantalla? 

![image](https://user-images.githubusercontent.com/38828911/143800637-88b9e50a-3220-418e-aff0-6ea5985040ff.png)

Debería figurar un mensaje de error donde está la flecha roja, esto me ayudaría a rastrear el problema. 

Un saludo

**Comment by Fenthral** [comment]
Hola me sale esto
![Sin título](https://user-images.githubusercontent.com/87309388/143805081-300d2a10-3b71-4be2-b589-b52f768bc395.png)

**Comment by emilianog94** [comment]
Genial, me sirve para intentar replicar el problema, gracias @Fenthral !
Es un error raro ya que aparece a los días o semanas de activar la extensión. Voy a estar atento para replicarlo en mi navegador así le busco la solución. 

Dejo el issue abierto para avisar apenas esté arreglado. Temporalmente para solucionarlo podés eliminar la extensión (eliminarla, no desactivarla) y añadirla de nuevo! 

Un saludo.
