### ISSUE TITLE
[Sugerencia] Opción para poner por default el precio base en el storefront

### ISSUE THREAD

**Issue by Wolf-93** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#33]
Hola, Emiliano. Antes que nada, te felicito por la extensión, me encantó.

Por esos azares de la vida, recién la descargo, imaginate que venia usando un Excel como calculadora jajaja. Estuve chumeando las opciones y no encontré, de ahi esta "sugerencia". ¿Es posible poner por default el precio sin impuesto en el store de un articulo? O sea, tal cual está ahora, pero al revés.

Usualmente suelo comparar descuentos actuales con ventas pasadas en Steamdb, a ver si vale la pena esperar a ahorrarse un pesitos más, porque a veces sucede que el publisher sube el precio (o el juego estaba en early access, etc), y se hace un poco confuso si uno se olvida que tiene los impuestos incluidos cuando compara.

Estoy seguro que estoy entre la minoría, tampoco es la muerte, y la verdad no sé cuánto tomaría implementar un botoncito así, no lo tomes como un reclamo, pero bueno, dejo la idea flotando.

Saludos!

**Comment by emilianog94** [comment]
Buenas @Wolf-93 , gracias por los comentarios!

Recuerdo que esto me lo sugirieron vía reddit unas cuantas veces: la posibilidad de ver los impuestos manualmente. Voy a tenerlo en cuenta para la próxima versión ya que a simple vista no parece ser algo complicado de implementar! 

Un saludo.

**Comment by emilianog94** [comment]
Hola @Wolf-93 ! 

Algo tarde sin embargo se agregó esta funcionalidad para setear el comportamiento default de Steamcito en la nueva versión v1.40. Adjunto link del release: https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/releases/tag/v1.40

Un saludo!
