### ISSUE TITLE
[BUG] Errores de calculo en paginas de Sales

### ISSUE THREAD

**Issue by Octaviorios** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#34]
**Describí el bug**
La extension calcula mal los precios en paginas especificas de sales como por ejemplo la corriente sale de Capcom

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí una pagina de sales como: https://store.steampowered.com/publisher/capcom/sale/CapcomPubSale?snr=1_4_4__118
2. Ver los precios.

**Capturas de Pantalla**
![image](https://user-images.githubusercontent.com/12775041/158384850-87cfd4d9-4dd6-4e9f-b9a9-4dee3140e355.png)

**Información de tu PC**
 - Navegador que estás usando: Firefox
 - Versión de la extensión: 1.10

**Comentarios adicionales**
Notese que algunos precios son exageradamente bajos y otros exageradamente altos

**Comment by Octaviorios** [comment]
Agrego un ejemplo:

Desde la pagina de la sale de Capcom, el juego "Ghosts 'n Goblins Resurrection" tiene el valor de 143604,45 ARS
![image](https://user-images.githubusercontent.com/12775041/158385806-6753e081-29df-4eb1-9a64-ce2373c65d79.png)

Si vamos a la pagina de steam del juego, el valor es de 1436,05 ARS (pareceria ser correcto)
![image](https://user-images.githubusercontent.com/12775041/158385988-4b0c9da6-c702-4de4-b462-228e856997b0.png)

**Comment by Octaviorios** [comment]
Por lo que veo, parece ser un problema simple relacionado con la cantidad de decimales por la cual multiplica el valor original.

**Comment by emilianog94** [comment]
Buenas @Octaviorios , te agradezco por el aviso, ya pude replicar el error y lo estoy revisando para ver qué puede estar pasando con el precio base. Te mantengo informado por acá,

un saludo!

**Comment by Octaviorios** [comment]
Buenisimo, gracias! Un saludo

**Comment by emilianog94** [comment]
Desactivando la extensión pude notar que el problema ocurre porque las secciones SALE de Steam están mostrando un formato de precio con comas invertidas (Coma en lugar de decimal, decimal en lugar de coma)

![image](https://user-images.githubusercontent.com/38828911/158520854-0342a290-b10b-4283-bca4-c4a95a550b9b.png)

![image](https://user-images.githubusercontent.com/38828911/158520902-10e1ac68-3b75-44d3-9304-e54487000e30.png)

Ejemplo Steam normal (correcto): **ARS $2.199,00** 
Ejemplo Steam en sección Sale (incorrecto):  **ARS$2,199.00**

Si bien lo ideal es que Steam lo solucione, voy a revisar una forma para solucionarlo desde el código!

**Comment by emilianog94** [comment]
Listo, se creó una comprobación de notación decimales y separador de miles y se solucionó el inconveniente en todas las páginas que tenían este error. 

![image](https://user-images.githubusercontent.com/38828911/158534023-d8c30389-87fc-473c-bb1d-89c40ec8d751.png)
 
Acabo de enviar la versión de Steamcito 1.2.0 a la Chrome Web Store y Firefox Addons, estimo que en 12-48hs ya se actualiza automáticamente en todos los navegadores (también podés actualizar manualmente desde chrome://extensions/ )

Temporalmente dejo el issue abierto por si surge algún otro inconveniente!

**Comment by Octaviorios** [comment]
Genial! Te ganaste unos cafecitos jaja. Gracias y saludos
