### ISSUE TITLE
[BUG] No funciona en items de "bundles", "collections" y similares en las tablas de la frontpage del store

### ISSUE THREAD

**Issue by Octaviorios** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#37]
**Describí el bug**
La extension no funciona en los items de "bundles", "collections" y similares en la frontpage del store

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí esta URL https://store.steampowered.com/
2. Fui a la tabla de "Top Sellers"
3. Apareció el error (Ver "Subnautica Deep Ocean Bundle", "Stellaris: Ultimate Bundle" y "Total War: THREE KINGDOMS COLLECTION" en el screenshot)

**Capturas de Pantalla**
![image](https://user-images.githubusercontent.com/12775041/168632429-33047f05-711c-4975-bf83-7d68da310260.png)
![image](https://user-images.githubusercontent.com/12775041/168633391-a80d99a2-898c-4b04-8b41-6c6613897571.png)
![image](https://user-images.githubusercontent.com/12775041/168632816-88d28d7e-8d88-449f-bbb9-0f575b417f41.png)

**Información de tu PC**
 - Navegador que estás usando: Firefox
 - Versión de la extensión: 1.20

**Comentarios adicionales**
Pareceria ser que la funcionalidad solo no funciona en las tablas (Top Sellers y demas) de la frontpage, ya que al entrar en la pagina especifica del bundle se calcula sin problema como se ve en el segundo screenshot.

Otra observacion> Parece que es algo intermitente. Por lo que veo, cuando abro la pagina por primera vez, funciona perfecto, pero si le tiro un refresh el problema aparece. Algo de cache tal vez?

**Comment by emilianog94** [comment]
Buenas Octavio!

Ahí lo estuve viendo, efectivamente hay un problemita en esa sección y pasa sólo en la primera carga. Si hacés CTRL + SHIFT + R (un hard refresh sin caché), el problema vuelve a ocurrir. 

Voy a investigar a qué se debe, muchas gracias por tu reporte!
