### ISSUE TITLE
[BUG] Steam Gift Cards

### ISSUE THREAD

**Issue by tobiasvasquez** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#38]
**Describí el bug**
Error a la hora de calcular el precio de las gifts card de steam

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí esta URL https://store.steampowered.com/digitalgiftcards/selectgiftcard
2. Hice X acción : Busque seleccionar una gift card, y me di cuenta que las ultimas dos, los precios estan mal calculados
3. Apareció el error

**Capturas de Pantalla**
De ser necesario, agregá capturas del problema
![image](https://user-images.githubusercontent.com/54642010/169667085-e67b7996-ca75-4aac-8aad-8ea5ccc807b0.png)

**Información de tu PC**
 - Navegador que estás usando:  Chrome version : 101.0.4951.67
 - Versión de la extensión: 1.20

**Comentarios adicionales**
Cualquier otro comentario que creas relevante para entender mejor el problema.

**Comment by emilianog94** [comment]
HBolaTobías! Ahí pude replicarlo, efectivamente se debe a un problema con los decimales en esas dos gift card. 
En el transcurso de esta semana semana voy a lanzar una actualización corrigiendo varios bugs de larga data, entre ellos este. 

Gracias por el reporte, un saludo!
