### ISSUE TITLE
pequeño pedido

### ISSUE THREAD

**Issue by jijoknotengo** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#39]
Hola buenas, recien doy con este steamcito y es genial. Solo un pequeño pedido ( si no es tan complicado ) se le podria poner opcion de prenderlo o apagarlo ? Como los adblock por ejemplo, el iconito arriba en la barra para prender o apagar el addon.

PD : ya lo sé, es bastante inutil el pedido pero me trauma no ver el precio publicado, mil gracias por el addon !!

**Comment by emilianog94** [comment]
Buenas @jijoknotengo , hasta ahora nunca lo hice pero voy a investigar para incluir la opción de desactivado en alguna próxima versión. 

Un saludo y gracias!

**Comment by JackER4565** [comment]
podes apagar la extension entera desde el panel de chrome y ya tambien!

**Comment by emilianog94** [comment]
Hola @jijoknotengo !

Si bien no se agregó esta funcionalidad, se creó una funcionalidad que en su lugar te permite setear el comportamiento default de Steamcito para que puedas ver siempre el precio publicado como primera opción si así deseás. 

Adjunto release: https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/releases/tag/v1.40

Saludos!
