### ISSUE TITLE
No funciona el Historial de compras

### ISSUE THREAD

**Issue by Yuarinaim** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#40]
Entre al historial y no funciona la conversión, ni tampoco me aparece el monto que deberían de devolverme 

para llegar al bug, no hice nada especifico, solo no anda la función del historial

**Información de tu PC**
 - Navegador que estás usando: Chrome
 - Versión de la extensión: 1.20

**Comment by emilianog94** [comment]
Hola @Yuarinaim , esto ya debería estar solucionado en la versión 1.21 que se lanzó la semana pasada. Cualquier cosa avisame.

¡un saludo!
