### ISSUE TITLE
[BUG] Impuestos aplicados a la moneda incorrecta en los importes mostrados.

### ISSUE THREAD

**Issue by maez92** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#41]
**Describí el bug**
Aplica la conversión al valor incorrecto al calcular los impuestos de una compra en que el importe original es en dólares y más abajo aparece en pesos. (Aplica el 65% sobre el dólar en lugar del peso)

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí esta URL https://secure.square-enix.com/
2. Seleccione MOGSTATION y posteriormente renovar suscripción vía STEAM PAYMENT (Al seleccionar el tipo de subscripción deriva el pago a la plataforma de Steam).
3. Apareció el monto sin modificar, y los dólares modificados y cambiado de USD a ARS

**Capturas de Pantalla**
![Screenshot_CON STEAMCITO](https://user-images.githubusercontent.com/84997092/178792240-1f97c958-c9b0-48d6-85a6-78429bc18d1a.png)

![Screenshot_SIN STEAMCITO](https://user-images.githubusercontent.com/84997092/178792243-542c882b-1eab-4189-9500-7cf39474210b.png)

**Información de tu PC**
 - Navegador que estás usando: Google Chrome
 - Versión de la extensión: V1.20

**Comment by emilianog94** [comment]
Hola @maez92 , desde ya te agradezco por el reporte! 

Intenté seguir los pasos sin embargo al no tener el juego base comprado me redirige a la URL para comprar el FINAL FANTASY XIV Online en pesos en vez de redirigir a la URL de compra en dólares con el bug. 

Voy a intentar encontrar otro juego que no requiera de un juego base para hacer esto, mientras tanto dejo el issue abierto. 

Un saludo!
