### ISSUE TITLE
[Sitio Web] Hay un error en los impuestos nacionales de sección Impuestos

### ISSUE THREAD

**Issue by Axelxp** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#42]
en la pagina de https://steamcito.com.ar/impuestos-hoy#impuestos-provinciales aparece que en
Retención de las ganancias 45%
Impuesto país 21%
Y Iva servicios digitales 8%

Debo decir que esa descripción esta mal ya que cuando compre un juego me salió que los impuestos era así:
Retención a las ganancias **35%**
**Impuesto País** 8%
**Iva servicios digitales** 21%

![Impuestos](https://user-images.githubusercontent.com/109365127/179258697-578b4380-2ece-4058-a701-091f39c41c18.jpeg)

Solamente hay un error de porcentaje y impuestos país y Iva tienen los porcentajes al revés, no es mucho pero con eso puedo aportar

**Comment by emilianog94** [comment]
Hola @Axelxp , gracias por notar que está invertido el % del Impuesto PAIS y el IVA. Voy a arreglarlo. 

Respecto al 35%, este subió a 45% el día 14/07. 

Un saludo!

**Comment by emilianog94** [comment]
Ya se encuentra correctamente modificado @Axelxp , gracias!
