### ISSUE TITLE
[BUG] correción impuestos

### ISSUE THREAD

**Issue by JUANCO2** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#43]
**Describí el bug**
Hay que cambiar el impuesto de 65% a 75% como se ve en la captura.

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí esta URL https://steamcito.com.ar/impuestos-hoy
2. Hice click en la diferencia de 1%
3. Apareció el error

**Capturas de Pantalla**
![Screenshot_2](https://user-images.githubusercontent.com/49576569/180631043-eed66b4b-a579-4d13-bf9e-d2e8a1eaa13c.png)

**Información de tu PC**
 - Navegador que estás usando: Opera
 - Versión de la extensión:1.21

**Comentarios adicionales**
No se si cuenta como bug pero lo dejo acá por las dudas .
Un saludo C: .

**Comment by emilianog94** [comment]
Buenas @JUANCO2 , gracias por avisarme de este detallito, ahí acabo de corregir el error de tipeo. 

Un saludo!
