### ISSUE TITLE
[BUG] Typo en manifest de Firefox

### ISSUE THREAD

**Issue by lmorand** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#45]
**Describí el bug**
Hay un typo en la línea 61 del manifest.json en Firefox: en vez de "run_at" dice "runt_at".

**¿Qué pasos seguiste para llegar al bug?**
1. Abrí about:debugging
2. Me apareció el siguiente warning sobre Steamcito: `Reading manifest: Warning processing content_scripts.2.runt_at: An unexpected property was found in the WebExtension manifest.`

**Información de tu PC**
 - Navegador que estás usando: Firefox 103.0
 - Versión de la extensión: 1.21

**Comentarios adicionales**
Supongo que el manifest difiere del que está en el repo porque Firefox todavía no soporta la version 3. ¿No sería mejor tener alguna constancia de esto en el repositorio?

**Comment by emilianog94** [comment]
Hola @lmorand , muchas gracias por notar esto! 
Efectivamente ese typo hace que la extensión no funcione en la sección /addfunds y /digitalgiftcards.

Como se upgradeó de Manifestv2 a Manifestv3 para Chrome en la última update, tuve que crear un manifest por separado para Firefox. Acabo de comittearlo al repo. Espero en los próximos días mandarlo a Firefox Addons! 

Dejo el issue abierto mientras tanto! Un saludo.

**Comment by emilianog94** [comment]
Tarde pero seguro @lmorand ! 

Ya se actualizó a la versión 1.30, se fixeó el typo y a partir de ahora el código de la versión de Firefox se encuentra subido al repo. 

Saludos, gracias!
