### ISSUE TITLE
[BUG] Se muestra tag <span> en historial de compras

### ISSUE THREAD

**Issue by eruizc-dev** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#46]
**Describí el bug**

Se visualiza un tag `<span class="emojis mate"> A </span>` en el historial de compras

**¿Qué pasos seguiste para llegar al bug?**

Se ve en: [https://store.steampowered.com/account/history](https://store.steampowered.com/account/history)

**Capturas de Pantalla**

![image](https://user-images.githubusercontent.com/58179604/184151491-d320afec-e4be-42de-a995-24aabc93a1ea.png)

**Información de tu PC**

 - Navegador que estás usando: Firefox 102.0.1
 - Versión de la extensión: 1.21

**Comment by eruizc-dev** [comment]
Viendo un poco más encontré que cuando la wallet está involucrada (total o parcial) anda bien ya sea para compras o refunds.

![image](https://user-images.githubusercontent.com/58179604/184153306-d40436cc-5446-4a37-911f-ff8aafc51f96.png)

**Comment by emilianog94** [comment]
Buenas @eruizc-dev , muchas gracias por el reporte. Efectivamente es un tema al momento de renderizar html, también pude replicarlo en Chrome. Voy a revisarlo para solucionarlo en la próxima actualización, dejo el issue abierto mientras tanto. 

¡Un saludo!

**Comment by emilianog94** [comment]
Hola @eruizc-dev , te confirmo que el bug ya se encuentra solucionado en la versión de hoy, gracias! 

un saludo.

**Comment by eruizc-dev** [comment]
Qué grande Emi!
