### ISSUE TITLE
[FEATURE] codigo para agregar punto (.) cada 3 digitos en el precio

### ISSUE THREAD

**Issue by JackER4565** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#47]
che te paso el siguiente codigo para agregarle el punto cada 3 digitos al precio, va en el helpers.js vofi!!

ANTES
[
![image](https://user-images.githubusercontent.com/94895169/187199402-956f745f-a8e3-4374-a897-e1c35b86e62a.png)
](url)
DESPUES
[
![image](https://user-images.githubusercontent.com/94895169/187199484-c6b3e915-53c9-4dc4-8b7d-163cfa59d572.png)
](url)
salu2

```
function numberToString(number){
    var parts = number.toString().split(".");
    parts[0]=parts[0].replace(/\B(?=(\d{3})+(?!\d))/g,".");
    return 'ARS$ '+ parts.join(",");
//    return `ARS$ ${number}`.replace('.',',');
}
```

**Comment by emilianog94** [comment]
Buenas @JackER4565 ! Muchas gracias por el dato, efectivamente con separador de miles se vería muchísimo mejor, voy a hacer unas pruebas para comprobar que no se rompa nada e intentar dejarlo implementado para la próxima versión.

Dejo el issue abierto mientras tanto, saludos!

**Comment by emilianog94** [comment]
Gracias @JackER4565 , está muy bueno el Regex, lo estoy testeando en todas las secciones y parece que no se rompe nada, si sale todo bien la próxima semana se actualiza la extensión con este enhancement. 

Saludos!

**Comment by emilianog94** [comment]
Hola @JackER4565 , el enhancement ya se encuentra incluido en el release de Steamcito 1.30 lanzado hoy.

Muchas gracias por el aporte!
