### ISSUE TITLE
[BUG] [Firefox] Steamcito se desactiva por predeterminado en juegos con precios bajos

### ISSUE THREAD

**Issue by fede-laria** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#48]
**Describí el bug**
Creo que esto es un bug. En los juegos con precios bajos (apróximadamente de 60 pesos o menos), Steamcito se desactiva por defecto. O sea, te muestra el precio normal, y para que muestre el precio con impuestos hay que hacerle click al precio. Esto no pasa en los juegos con precio más alto.

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrí Steam en Firefox (https://store.steampowered.com/)
2. Buscar el juego "Original War" en el buscador de Steam (a modo de ejemplo)
3. Hacer click en el juego para ir a la página de la tienda.
4. Ahí se puede ver que el precio aparece sin impuestos, con el símbolo "$" al lado.

**Capturas de Pantalla**
![steamcito](https://user-images.githubusercontent.com/43150728/189483003-10126cc9-2615-4aad-8576-29264d1efa12.png)

**Información de tu PC**
 - Navegador que estás usando: Firefox Developer Edition
 - Versión de la extensión: 1.21

**Comentarios adicionales**
 Uso Firefox, no sé si también pasará en otros navegadores.

**Comment by emilianog94** [comment]
Buenas @fede-laria , te agradezco por el reporte.

Intenté replicarlo con ese producto en particular y se me ve correctamente. 

¿Puede ser que estés logueado y que tengas suficiente saldo de Steam Wallet para adquirir el juego? [Esto es una funcionalidad core de Steamcito](https://steamcito.com.ar/funcionalidades), mostrarte el precio con saldo como opción recomendada cuando tengas saldo suficiente.

Quedo a la espera, saludos!

**Comment by fede-laria** [comment]
@emilianog94 Debe ser eso, disculpas!
