### ISSUE TITLE
CUIT

### ISSUE THREAD

**Issue by al3m4tu** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#50]
Estaba viendo que están también devolviendo plata del 2021. entre al afip con la guía y me sale esto.
y en ninguna parte de la guía habla del CUIT.
Me gustaría que lo incluyas porque tengo miedo de meterle mano y hacer cualquier cosa.
Desde ya gracias
![14344193db37231b5db8113aed6c7eab](https://user-images.githubusercontent.com/53633597/193426800-b4a27f21-e4ae-41ae-a0af-4ed4322042e1.png)

**Comment by emilianog94** [comment]
Hola @al3m4tu ! 
Recién veo esto que me indicás. 

En la captura que mostrás te están pidiendo que tengas el CUIT. Apenas saques el CUIT y entres a la sección donde cargás las devoluciones e ingreses un período, (Ej: 202101 que sería Enero de 2021) te va a aparecer un cartel que te dice que no es posible cargar una devolución para el período solicitado. 

Cualquier otra consulta avisame. 
Un saludo y perdón la demora!
