### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lucypero** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#51]
https://store.steampowered.com/app/480490/Prey/

Prey decia que estaba $699.56 pero tuve que pagar $799.51

2022-10-20

![image](https://user-images.githubusercontent.com/11927498/197080162-5ecc9abf-8e32-4972-a127-697ae5ef61e7.png)

**Comment by emilianog94** [comment]
Hola @lucypero !

Desde la semana pasada si gastaste más de 300 dólares en compras al mes, el impuesto nacional pasa del 75% al 100%. 
Si es tu caso podés configurar Steamcito para mostrar el 100% desde el configurador de impuestos. 

Muchas tarjetas (billeteras virtuales como Lemon o Ualá según reportes), se están atajando y están cobrando de prepo un 100% a todos los consumos por más que no hayas llegado al tope de 300. Si este es tu caso te recomiendo que contactes al soporte de la tarjeta para que te devuelvan la diferencia mal cobrada.

Un saludo!
