### ISSUE TITLE
[BUG] 🪲 Se rompen los resultados de búsqueda: desaparecen items 🐛

### ISSUE THREAD

**Issue by ownchoice** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#52]
**Describí el bug**
Simplemente al hacer una búsqueda en Steam, se rompe la lista de resultados y en varios de ellos no se muestra nada excepto la imagen del juego. No se pueden ver datos como el precio, el nombre, etc.

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Hacer una búsqueda en la página de Steam.
2. Por ejemplo: "Resident Evil" ([link](https://store.steampowered.com/search/?sort_by=_ASC&term=Resident%20Evil%20&category1=998))
3. Los resultados parpadean y desaparece todo menos su thumbnail en algunos de ellos.

**Capturas de Pantalla**
Capturas del bug usando el ejemplo anterior:

Brave:
![image](https://user-images.githubusercontent.com/22414323/204117560-5279e95f-dced-4fb3-a39c-9ef0cb534838.png)

Firefox:
![image](https://user-images.githubusercontent.com/22414323/204117562-51f95102-a863-4485-b829-0820c17d94d9.png)

**Video**

[https://www.dropbox.com/s/o9am0axhtw8b131/firefox_7O1P5FyGW4.mp4?dl=0](https://www.dropbox.com/s/o9am0axhtw8b131/firefox_7O1P5FyGW4.mp4?dl=0)

**Información de tu PC**
 - Navegador que estás usando: 
    - Firefox
      - Con perfil limpio 
      - Solo Steamcito instalado, sin **ninguna otra extensión**
      - Versión 107.0 (64-bit)
    - Brave:
      - Con perfil limpio 
      - Solo Steamcito instalado, sin **ninguna otra extensión**
      - Version 1.45.131 Chromium: 107.0.5304.110 (Official Build) (64-bit)
 - Versión de la extensión: **1.30**

**Comment by emilianog94** [comment]
Buenas @ownchoice, muchas gracias por tu reporte!

Tras revisar esto que pasaste, noté que es un problema de estilos en esta sección específica. Cuando supera cierto ancho debido a la cantidad de números que tiene el precio, todo el contenido de la fila va hacia abajo y por ende desaparece.

En el transcurso de esta semana lanzo la actualización para corregirlo. Dejo el issue abierto hasta ese entonces.

Un saludo!

**Comment by LucianoOrtega** [comment]
Además de este error sucede algo mas, la función de cliquear el precio y que te aparezca el de Steam (Sin impuestos) no funciona tampoco en esta sección, adjunto video.

https://clipchamp.com/watch/9ch12dFRTDk

**Comment by emilianog94** [comment]
Hola! Se acaba de deployear la nueva versión de Steamcito que entre otras cosas arregla este bug. 

![image](https://user-images.githubusercontent.com/38828911/210909565-73e19f19-9267-42cf-b621-dfb390ade0ba.png)

@LucianoOrtega , gracias por el aporte, efectivamente pude comprobar que esto sólo ocurre en esta sección cuando el producto posee precio de oferta, para el resto de los precios funciona correctamente, voy a revisarlo para un nuevo deployment, muchas gracias!!
