### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by francopelli-dev** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#56]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Tengo saldo en la cartera de steam y algunos precios me aparecen en pesos steam y otros en pesos matecito. Pero quiero ver todos los precios en peso steam. Más que nada para ver cuanto tengo que poner de diferencia entre el saldo y lo que sale.

**¿Qué te gustaría que ocurra?**
Boton que alterne los precios entre matecito y peso steam

**Alternativas que hayas considerado**
Una o más alternativas que se te hayan ocurrido para solucionar el problema

**Comentarios Adicionales**

**Comment by emilianog94** [comment]
Hola @francopelli-dev !

Te agradezco por la sugerencia. 

> Más que nada para ver cuanto tengo que poner de diferencia entre el saldo y lo que sale.
Para este caso en particular la extensión cuenta con una funcionalidad para cuando tenés saldo en la Steam Wallet. Dentro de la pestaña del carrito podés ver cuantos pesos te faltan en tu Steam Wallet para comprar el producto.

De todos modos para la próxima versión ya se encuentra planeada la funcionalidad para desde las opciones alterar el comportamiento por defecto de Steamcito. 
Un saludo!

**Comment by emilianog94** [comment]
Hola @francopelli-dev , te confirmo que en la nueva versión de Steamcito se agregó esta funcionalidad, te adjunto el link al release: https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/releases/tag/v1.40

Un saludo!
