### ISSUE TITLE
[FEATURE] Incluir impuesto de steam partner

### ISSUE THREAD

**Issue by Neyunse** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#57]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**

Dado que steamcito solo esta activado para la parte de la tienda, supongo que se podría implementar también para la pagina de compra de Steam Direct (que es para adquirir la posibilidad de subir juegos a steam) el mismo cuesta 100 dolares, y actualmente me marca 10 mil pesos argentinos; sin embargo, el precio esta sin impuestos. Creo que seria mas informativo para los devs argentinos el incluir la posibilidad de que steamcito muestre el precio **"real"**

**Comentarios Adicionales**
![image](https://user-images.githubusercontent.com/36079551/220487755-2ba9fcd5-6758-4c96-9c2b-d093cd123b9f.png)

url: `https://store.steampowered.com//checkout/?cart=5066023942796707070&partner_redirect=newpartner%2Fpaidfee%2F`

**Comment by Neyunse** [comment]
ah, es un bug xd

**Comment by emilianog94** [comment]
Hola @Neyunse , recién veo esto!

Que cagada que Steam esté redirigiendo mal. 

Lamentablemente no me es posible agregar nuevos paths a la extensión, cuando agregás un nuevo path por cuestiones de seguridad Chrome elimina y desactiva la extensión en todos los navegadores, lo cual no es ideal y puede llevar a mucha confusión.

En este archivo se encuentran todos los dominios en los cuales Steamcito está activado:
https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/blob/master/chrome_extension/manifest.json

Espero que Steam nunca se le de por cambiar el store.steampowered.com porque cagamos jaja. 

Saludos!

**Comment by Neyunse** [comment]
@emilianog94  Creo que se podria implementar un parche a la url en js y redirigir a la pagina correcta. Digamos: 

```javascript

let url_to_redirect
const href = window.location.href

if (href.include(".com//")){
    url_to_redirect= href.replace(".com//", ".com/");
   window.location.href = url_to_redirect
}

```

basicamente lo que esto hace es arreglar la url, sin embargo, tambien hay que contemplar que `location.pathname` no tenga `//` en otra parte de la url, por ejemplo: `https://store.steampowered.com/checkout//`. aqui aparece al final del pathname.

desconozco como funciona google store, pero "creo" que con esto no deberia chillar google xd
