### ISSUE TITLE
[FEATURE] Mostrar precio con impuestos en el filtro de precios

### ISSUE THREAD

**Issue by elivinsky** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#65]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Es raro que si uso el filtro de precio al buscar juegos en la tienda no estoy filtrando por el precio real sino por el precio sin impuestos.

**¿Qué te gustaría que ocurra?**
Estaría bueno que el filtro mostrara el límite de precio con impuestos incluídos.

**Alternativas que hayas considerado**
-

**Comentarios Adicionales**
<img width="223" alt="Screenshot 2023-04-30 at 17 22 49" src="https://user-images.githubusercontent.com/11669061/235374586-939fb214-ba3b-4ee0-939f-617e229b350a.png">

**Comment by emilianog94** [comment]
Buenas @elivinsky !

La verdad no había visto este issue, perdón la demora!

Me parece un buen detalle, voy a implementarlo en la próxima versión.
Dejo el issue abierto para actualizar cuando esté listo.

Un saludo y gracias!!

**Comment by emilianog94** [comment]
Buenas @elivinsky , te confirmo que se acaba de implementar esto en la nueva versión que se mandó el día de hoy.

Un saludo, gracias!

**Comment by elivinsky** [comment]
@emilianog94 Gracias a vos!
