### ISSUE TITLE
[FEATURE] Mostrar ambos precios al mismo tiempo

### ISSUE THREAD

**Issue by Miltxn** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#66]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Muchas veces quiero saber el precio con y sin impuestos, y tener que ir cambiando uno por uno resulta un poco molesto. 

**¿Qué te gustaría que ocurra?**
Sería muy cómodo poder ver los precios con y sin impuestos a la vez.

**Alternativas que hayas considerado**
N/A

**Comentarios Adicionales**
Dejo una captura super pedorra de la idea jeje
Muy genial la idea y muy bien aplicada btw! ♥
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/11286210/f35d11d5-5152-4b20-a428-a4b3c7973842)

**Comment by emilianog94** [comment]
Hola @Miltxn !

Te agradezco por la sugerencia!
Te cuento, en la versión inicial de Steamcito en 2020 (antes del lanzamiento oficial), la extensión operaba exactamente de esta manera, con todos los precios visibles. 

En pruebas con usuarios amigos, saltó a la vista la molestia que producía esto ya que las páginas eran mucho más largas para scrollear por la duplicación de la altura del contenedor de precios y a su vez aquellos juegos que se encontraban en oferta habían cuatro precios a la vista, lo cual hacía muy molesta la visualización de precios y había que caer en cambios de tamaño que perjudicaban la UI

Por esta razón es que quedó la versión actual que es lo más cercano a cómo un usuario espera visualizar la tienda de Steam con la menor modificación posible. 

Un saludo!
