### ISSUE TITLE
[BUG] [Firefox] El saldo en el wallet no se renderiza correctamente con emojis retrocompatibles

### ISSUE THREAD

**Issue by jschuhmann47** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#70]
**Describí el bug**
En LibreWolf (Firefox) al entrar a la página principal con los emojis retrocompatibles, no se renderiza el saldo correctamente.

**¿Qué pasos seguiste para llegar al bug?**
1. Entrar a la página principal de Steam
2. Tener los emojis retrocompatibles activados
3. Notar que arriba a la derecha donde se indica el saldo, se muestra incorrectamente

**Capturas de Pantalla**
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/76596375/a9b26fac-f725-46cb-8326-36a4483c9780)

**Información de tu PC**
 - Navegador que estás usando: LibreWolf 118.0.1-1
 - Versión de la extensión: 1.41

**Comentarios adicionales**
Con los emojis normales/recomendados no sucede el problema:
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/76596375/d0b8d5cb-8f25-463c-87d2-ddbf0356e0af)

y aguante la extensión (?

**Comment by emilianog94** [comment]
Hola @jschuhmann47 ! 

Gracias por avisar, ya pude replicar el bug que indicás. En el transcurso de esta semana voy a lanzar una nueva versión contemplando la resolución de este bug.

Un saludo!

**Comment by emilianog94** [comment]
Buenas @jschuhmann47 , te confirmo que ya se subió el fix a la nueva versión de Firefox. Cualquier cosa me avisás.

Un saludo y gracias!

**Comment by jschuhmann47** [comment]
Gracias a vos!
