### ISSUE TITLE
[FEATURE] [OPERA] Desactualizado

### ISSUE THREAD

**Issue by Nacho96la22** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#71]
Buenas quiera avisarte para saber que el extensión de opera no esta actualizado que me fije q tiene 0,70 versión que es muy viejo. 
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/143468294/3d3faf30-5416-4adb-b490-1a59c139b2a4)

**Comment by emilianog94** [comment]
Buenas Nacho! 

Le había dejado de dar soporte a la tienda de Opera ya que la primera vez que subí la extensión tardaron cinco meses en revisarla, cuando en Firefox o Chrome el proceso toma menos de una semana.

En base a esto que me comentaste iba a anotarme actualizarla, sin embargo revisé que desde el año pasado ### Opera soporta de forma nativa la posibilidad de instalar extensiones de Chrome WebStore. 

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/2fa41b5e-db7f-4978-a047-4b14ef85f4b1)

En base a esto voy a eliminar la extensión de la tienda de Opera y te recomiendo que la descargues de Chrome desde este link:
https://chrome.google.com/webstore/detail/steamcito-steam-con-impue/fcjljapncagfmfhdkccgnbkgdpbcefcj?hl=es&authuser=2

Un saludo! Muchas gracias.
