### ISSUE TITLE
Compras previas al aumento [FEATURE]

### ISSUE THREAD

**Issue by Wossgebber** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#72]
Sólo ajustar el valor de compras previas al 10/10/23. Me toma el valor final del carrito por 100% en lugar del 75% original. Excelente herramienta!

**Comment by emilianog94** [comment]
Se implementó esta nueva funcionalidad en la versión V3.30, a partir de ahora hay un histórico de impuestos que aplica a la sección Historial :) 

https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/releases/tag/v3.30
