### ISSUE TITLE
[BUG] Precio total del carrito no se muestra correctamente

### ISSUE THREAD

**Issue by ownchoice** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#73]
## Descripción

Me gustaría poder ver el total del carrito siempre con y sin impuestos, que me muestre ambos importes o poder cambiar entre ellos. Dado que normalmente la extensión permite hacer esto en todos los otros lugares, considero que puede ser categorizado como un bug. Además no es consistente entre los distintos ajustes, mostrando algunas veces una cosa y otras veces otra cosa.

Mi problema es que con algunas configuraciones me muestra el precio total del carrito con y sin impuestos, y con otras solo veo uno y no tengo opción de ver el otro.

- Preferencia de precios: Recomendado → Solo coste total con impuestos
- Preferencia de precios: Forzar precios con tarjeta→ Solo coste total con impuestos
- Preferencia de precios: Forzar precios con saldo→ Ambos costes totales

**Todo esto lo probé sin tener saldo en la cuenta de Steam.**

## Capturas de Pantalla

Preferencia de precios: Recomendado
![steamwebhelper_WX9NPJlh9X](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/22414323/7080bcfe-8ed7-41a5-b671-079978a2335f)

Preferencia de precios: Forzar precios con tarjeta
![steamwebhelper_TS8fnCoJBh](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/22414323/23067017-ab8c-432d-8fbd-f9703ba948fa)

Preferencia de precios: Forzar precios con saldo
![steamwebhelper_5CFKE1yDAe](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/22414323/3f0c7717-f245-44ba-81e2-6dd4d216a335)

## Pasos para llegar al bug

1. Agregar productos al carrito
2. No tener saldo en la cuenta
3. Ir al carrito y mirar el total
4. Cambiar la configuración de Steamcito de "Preferencia de precios"

## Información de mi PC
 - Navegador: Brave Version 1.59.117 Chromium: 118.0.5993.70 (Official Build)  (64-bit)
 - Versión de la extensión: 1.42

**Comment by emilianog94** [comment]
Buenas @ownchoice ! 

Gracias por el aviso, efectivamente hay inconsistencias en estas opciones como el caso que notás que eligiendo la preferencia con saldo aparecen ambos con el desglose de impuestos. 

Voy a revisar esto para ver cómo hacerlo más consistente.

Un saludo y gracias!

**Comment by emilianog94** [comment]
Buenas! Te confirmo que esta mejora ya está disponible en la nueva versión de Steamcito que fue lanzada el día de hoy (Steamcito 2.2)

Un saludo y gracias!
