### ISSUE TITLE
[BUG] Icono del mate (arriba de todo a la derecha) desaparece al hacer zoom y no está en el menu de la hamburguesa

### ISSUE THREAD

**Issue by RealAngelFerTorres** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#75]
**Describí el bug**
Cuando hacés mucho zoom o usando un celular, no se ve el icono del mate para abrir el menú desplegable de la configuración de la extensión. Normalmente, la página de Steam es responsive y oculta cosas que pone en el menú de la hamburguesa al redimensionar la página, pero el icono del mate desaparece y está ausente dentro de la hamburguesa.

**¿Qué pasos seguiste para llegar al bug?**
1. En Firefox: Usar el zoom al 220% o que el width sea menor o igual a 910px

**Capturas de Pantalla**
No es necesario.

**Información de tu PC**
 - Navegador que estás usando: Firefox 118.0.2 (64-bit)
 - Versión de la extensión: 2.0

**Comentarios adicionales**
Gracias por la extensión :)

**Comment by emilianog94** [comment]
Hola @RealAngelFerTorres !

Efectivamente Steam modifica su layout a partir de los 910px. Como esta es más bien una vista mobile y la extensión no posee soporte oficial para dispositivos móviles (sólo puede correrse en dispositivos móviles en Android usando un navegador específico), nunca le hice compatibilidad Mobile. 

Esto es un poco complejo ya que, como Steam modifica todo el layout hay que hacer varios cambios, como por ejemplo modificar la extensión para obtener el saldo de Steam Wallet y demás. 

Por estas razones al menos por el momento no tengo en mis planes hacer una adaptación de Steamcito a Mobile. Tal vez en el futuro si hay más navegadores que acepten complementos de manera oficial podría revisarlo.

Un saludo y gracias!
