### ISSUE TITLE
[FEATURE] Opción para deshabilitar el cuadro de "¿Cómo es el precio regional?" y "Cotización del dólar referencial"

### ISSUE THREAD

**Issue by ZoruaLoL** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#81]
Arrastra información importante sobre el juego hasta muy abajo de la página, y la verdad se me hace un tanto redundante saber si se respetó o no el precio sugerido por Valve, sobre todo desde que se dolarizó la tienda, dónde ya no se van a dar casos donde diga que el juego es "barato" y cuando el precio está por encima del sugerido en realidad es el mismo precio que en USA

**Comment by emilianog94** [comment]
Buenas @ZoruaLoL !

Efectivamente estoy notando que el mensaje arrastra información que puede ser importante. Por otro lado sí tenemos casos en los cuales un juego está barato aún posterior a la dolarización. Acá hay unos ejemplos que pude ir encontrando en el transcurso de hoy: 
https://store.steampowered.com/app/1145360/Hades/
https://store.steampowered.com/app/237930/Transistor/
https://store.steampowered.com/app/1293830/Forza_Horizon_4/
https://store.steampowered.com/app/2512430/Void_Survivors/
https://store.steampowered.com/app/422970/Devil_Daggers/

Imagino que muchos más!
En base a lo que comentás voy a trabajar en una funcionalidad que te permita, desde las opciones de Steamcito, ocultar esta barra o mostrarla minificada. 

Un saludo y gracias!

**Comment by lgallard** [comment]
Paso para comentar que esta funcionalidad me parece muy útil, y que al parecer en la versión 3.11 dejó de funcionar. 

En mi caso la uso para evaluar si comprar a un precio barato o adecuado o si por el contrario si está caro dejarlo en la lista de deseados.

**Comment by emilianog94** [comment]
> Paso para comentar que esta funcionalidad me parece muy útil, y que al parecer en la versión 3.11 dejó de funcionar.
> 
> En mi caso la uso para evaluar si comprar a un precio barato o adecuado o si por el contrario si está caro dejarlo en la lista de deseados.

Hola @lgallard ! Gracias por avisar. Hoy abrieron un issue por esto mismo https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/issues/85 , por el momento no estoy pudiendo replicarlo. 

Si todavía te sucede este error, si podés dejar la captura de la consola me serviría muchísimo para entender qué puede estar pasando!

**Comment by lgallard** [comment]
@emilianog94 dejé capturas en #85

**Comment by emilianog94** [comment]
Hola @ZoruaLoL , te confirmo que esta funcionalidad acaba de ser agregada en Steamcito v3.13 y será lanzada en el transcurso de hoy. 

El menú lateral cuenta con una opción que al habilitarla la barra lateral se reduce a un 10% de su tamaño original para no interferir con la información nativa de la tienda. 

![v313-0](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/d88862ca-e87a-4cdd-acaa-256dfb3324fa)

![v313-01](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/fb43fb5f-8df8-4715-ab81-68c08f4a5f42)

Más detalles de la actualización acá: https://steamcito.com.ar/changelog

Un saludo y gracias!
