### ISSUE TITLE
[BUG] No aparece el precio regional

### ISSUE THREAD

**Issue by Karrux** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#82]
Al abrir cualquier página de tienda de steam se muestra el precio bien pero al costado solo aparece el apartado de Cotización del dólar referencial y no aparece el de Precio Regional sugerido. Esto no me sucedía antes. Ya probé deshabilitando todas las demás extensiones o habilitando y deshabilitando Steamcito.

Ejemplo:
1. Abrí esta URL https://store.steampowered.com/app/582010/Monster_Hunter_World/ o https://store.steampowered.com/app/1145360/Hades/
y en las capturas se puede ver que solo aparece la Cotización del dólar referencial.

**Capturas de Pantalla**
![imagen](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/151770242/3aaf4a26-037d-43a8-90b5-9ee5bd77c334)

**Información de PC**
 - Navegador que estás usando: Mozilla Firefox Version 120.0 (64-bit)
 - Versión de la extensión: 3.0

**Comment by emilianog94** [comment]
Buenas @Karrux !

Esto ocurre porque la barra de precios regionales se agregó en la versión 3.10, y actualmente en Firefox estás corriendo la versión 3.0 .

Si bien la 3.10 fue lanzada ayer, Firefox tarda varios días en aprobar una nueva versión. ¡Imagino que para fines de esta semana se te va a actualizar automáticamente!

Un saludo y gracias.
