### ISSUE TITLE
[BUG] Cotización del dolar referencial

### ISSUE THREAD

**Issue by SrPY** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#83]
Lo primero que tengo que decir que el trabajo que haces es enorme, fantástico. Pero tengo que comentarte que con la nueva dolarización de la tienda, el dólar referencial que has puesto no es correcto ya que el dólar al que cotizan los juegos con impuestos es con el dólar tarjeta, hice la prueba con el W.o.r.m.s y da exacto el precio. Es una cagada por que tendrías que actualizar diariamente, ya que todos los tipos de cambio en este país, como sabes bien, varía constantemente.

**Comment by emilianog94** [comment]
Buenas tardes @SrPY !

Estoy viendo esto que comentás, puede ser una confusión. 

La cotización del dólar referencial es basada en el dólar oficial y viene automáticamente cada 2 horas.

Los precios de los juegos se componen en la siguiente operación: 
Precio base en dólares * Cotización del dólar * Total de impuestos

Ejemplo en un juego de 9.99 USD:
9.99 * 374 * 2 = 7.472

Los valores que te ofrece Steamcito son aproximados muy cercanos al valor final debido a que cada entidad tiene su propia cotización. 

Un saludo!

**Comment by SrPY** [comment]
Hola de nuevo. Tu explicación es correcta, aplica perfecto... Pero para alguien que no entienda muy bien como es el tema de impuestos o dólar tarjeta va a ser muy confuso, fiándose de el valor de $374,33 no va a entender si tiene que basarse en eso o el doble con el impuesto que conformaría el dólar tarjeta y sería el precio final (De hecho ayer vi un streamer Argentino que le preguntaban incluso si tendrían que pagar el doble del precio especificado en dólares, es decir un juego que vale $19,99, pagarlo 40$ hay mucha confusión). Te lo digo por que he visto videos en Youtube y mucha gente pregunta todas estas cuestiones, hay mucha desinformación y poco entendimiento. Capaz podrías agregarle una leyendita chiquita explicando este ejemplo que me describiste o directamente agregando que el precio final de un juego pagado con tajeta (Ya que la mayoría compra de esta manera y no con saldo de la cartera de Steam) sería el doble del dólar referencial especificado. Más que nada te lo digo por el bajo entendimiento del tema. Gracias igualmente por el trabajo, facilita muchísimo las cosas.

**Comment by emilianog94** [comment]
Ahora entiendo @SrPY , muchas gracias por el ejemplo, no lo había pensado así! 

Te confirmo que, aprovechando que subieron los impuestos, acabo de lanzar una actualización implementando este cambio. Efectivamente es mucho más claro ahora. 

Ya se encuentra disponible la versión 3.11 que aplica esta mejora que indicaste acá:

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/0b24abe2-4d60-4fc7-92a3-05de70ad634b)

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/1b35ddbe-41a9-4c43-9e21-f5e350cde5e5)


Un saludo y muchas gracias!
