### ISSUE TITLE
[BUG] No se muestra la comparativa del precio recomendado por Steam vs el Actual

### ISSUE THREAD

**Issue by Awpii** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#85]
**Describí el bug**
No aparece el precio regional recomendado por steam vs el demostrado, con la comparativa

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Abrír cualquier item en la tienda de Steam
2. No aparece la comparativa de precios

**Capturas de Pantalla**
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/73240369/ceb98ac1-2794-485d-9c9d-49adae52b8ed)
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/73240369/954978c9-d2b1-4f8b-ab9d-0d91082631bb)

**Información de tu PC**
 - Vivaldi 6.4.3160.44 (Stable channel) (64-bit)
 - Steamcito v3.11

**Comment by Awpii** [comment]
Agrego nota: Reinstalar soluciona brevemente el bug y vuelve a pasar.

**Comment by emilianog94** [comment]
Buen día @Awpii , gracias por tu reporte! 
Según veo en las capturas desaparece toda la barra lateral, incluyendo la de la cotización del dólar. 

Estuve revisándolo tanto en Chrome como en Vivaldi y no puedo replicarlo al menos por el momento. Voy a estar atento a lo largo del día por si llega a ocurrirme.

En el caso de que vuelva a ocurrirte (veo que lo solucionaste reinstalando), ¿podrías pasarme una captura de pantalla de la consola de Javascript del navegador? Para esto tocás F12 y clickeás en la pestaña Console: 

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/1d6fa61d-aa25-40fe-81a6-eadc68ae7b73)

Con esa información podría ver exactamente qué función/variable está fallando. 

Muchas gracias desde ya! quedo atento.

**Comment by emilianog94** [comment]
Buenas! Ahora que te anda bien la funcionalidad de la Sidebar la captura no me va a servir porque la consola va a estar vacía.
Cuando vuelva a desaparecerte la barrita va a figurar el error en la consola indicando qué falló.

Gracias!

**Comment by Awpii** [comment]
Dale, quedo atento a que pase de vuelta! Cualquier cosa te aviso.

**Comment by lgallard** [comment]
@emilianog94 dejo mi captura por si te sirve.

PD: Hoy activé otras extensiones relacionadas Steam pero el error ya pasaba de antes.

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/6194359/56ba4ee8-aa48-4bf9-9658-158850a4c320)

**Comment by emilianog94** [comment]
Gracias @lgallard ! 

En base a la captura veo que es la función de la cotización del dólar que se está inicializando después que la barra lateral. Acabo de lanzar una actualización que fuerza la carga de la cotización del dólar para así evitar este error. 

La versión 3.12 ya está disponible y se actualizará la extensión a lo largo del día, debería arreglar este problema. 

Dejo el issue abierto para que me avisen! 

Un saludo y gracias

**Comment by Awpii** [comment]
Te parece si lo dejamos abierto hasta el miercoles que viene y vemos si vuelve a pasar? 

Igual seguro eso lo soluciona.

**Comment by Awpii** [comment]
Buenas, parece que esto está resuelto! Cierro el caso.
