### ISSUE TITLE
[Pregunta] Acerca de los impuestos

### ISSUE THREAD

**Issue by Pitu** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#87]
Disculpa que habra una pregunta aca pero no vi otra forma de contacto y no estaba en el FAQ.
Tengo una duda sobre como se estan calculando los impuestos actualmente en steamcito.

Voy a poner como ejemplo el Remnant II al dia de hoy, con la siguiente info

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/7425261/5ef6cf55-f8f1-4f4c-be59-91a636c1752b)

Segun entiendo con esta data, el precio que steamcito esta mostrando activamente es el precio en USD * cotizacion del dolar.  O sea USD 34.99 * 957.21 ARS = ~33.493 ARS.

Pero mas alla de la cotizacion del dolar, no estan faltando los impuestos en la cuenta? Percepcion de ganancias, impuesto pais y bienes personales? Sin hablar del nuevo https://www.infobae.com/economia/2023/11/23/dolar-tarjeta-el-gobierno-dispuso-un-incremento-y-el-tipo-de-cambio-que-se-aplica-a-compras-en-el-exterior-se-acerca-a-los-1000/

Puede que este equivocado y disculpas si es asi, pero no deberia el precio final ser calculado con todos estos impuestos sumados al PRECIO * COTIZACION USD?

Gracias!

**Comment by emilianog94** [comment]
Hola @Pitu !

Te confirmo que la cotización del dólar referencial tiene absolutamente todos los impuestos agregados.

Esta se compone del Precio del dólar más los impuestos nacionales/provinciales.
Le agregué abajo en el detalle que es el promedio del tipo de cambio minorista más todos los impuestos agregados. 

Por esto es que no hay que hacer ningún cálculo adicional, la cotización es la final! 

Un saludo.

**Comment by Pitu** [comment]
@emilianog94 te agradezco una banda la explicacion. Muchas gracias!
