### ISSUE TITLE
[BUG] No renderizan los emojis en versiones desactualizadas de Windows 10

### ISSUE THREAD

**Issue by Fede0GZ** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#9]
Hola, cuando entro a Steam, no me aparece el matecito, ni el signo de pesos, de lo contrario, lo que me aparece es un precio tachado, y a la derecha un precio nuevo seguido de un cuadradito transparente.

1. Añadí la extención a Google Chrome
2. Entré a la página de Steam, https://store.steampowered.com/?l=spanish
3. Y ahí estuvo el error.

Captura de Pantalla:
https://prnt.sc/vrbtkw

- Navegador que uso: Google Chrome
- Versión de la extensión: Según Chrome Web Store, es la versión 0.42 y la fecha de actualización fue el 26 de noviembre del 2020.

No creo que sea un problema mío ya que lo único que hice fue agregar la extensión, y tuve el error. Siempre me funcionó bien el navegador web, y nunca tuve ningún problema con Google. Quizás está mal posicionada la imagen o algo así. 
Desde ya, gracias por la atención y disculpen por las molestias.

**Comment by emilianog94** [comment]
Hola @Fede0GZ , gracias por reportar. 

De acuerdo a la captura de pantalla que me pasaste, tu sistema operativo no cuenta con soporte para esos emojis. 

¿Me indicarías qué versión de Windows 10 estás usando así investigo una potencial solución para tu caso particular?
Para eso vas a Inicio/Información del Sistema
![image](https://user-images.githubusercontent.com/38828911/100467505-55195400-30b1-11eb-9b8b-e9f947b8ae37.png)

**Comment by Fede0GZ** [comment]
Hola Emiliano, gracias por contestarme tan rápidamente, te dejo una screenshot de lo que me pone en la información del sistema:
![Screenshot_1](https://user-images.githubusercontent.com/53465976/100478484-1217aa80-30ca-11eb-821d-5146c4e125ef.png)

**Comment by emilianog94** [comment]
Gracias Fede! Eso explica todo. 

El soporte para Emojis fue incluido en Windows 10 en la versión 10.0.18362 a través de la actualización 1903 de Mayo de 2019 
https://www.windowscentral.com/whats-new-input-windows-10-may-2019-update

Me acabo de enterar ya que es la primera vez que alguien me reporta esto. Asumí que los emojis estaban en todas las versiones de Windows 10. 

**¿Cómo solucionarlo?**
Actualmente Steamcito cuenta con un sistema de compatibilidad donde se muestra un símbolo de mate y $, pero sólo está disponible en Windows 7, Windows 8, Windows 8.1 y Ubuntu. Se ve así: 
![Sin título1](https://user-images.githubusercontent.com/38828911/100479836-22ca1f80-30ce-11eb-8078-43cba42a3e55.png)

Entre la primera y segunda semana de Diciembre voy a lanzar la v0.5 para que, mediante un menú contextual, puedas seleccionar el estilo de emoji, así podés cambiar manualmente a los emojis "planos". 

Dejo abierto el issue para avisar apenas esté la nueva versión lista. 

¡saludos!

**Comment by Fede0GZ** [comment]
Buenísimo, gracias por la atención. Espero la nueva versión <3

**Comment by emilianog94** [comment]
Hola @Fede0GZ , ¡la funcionalidad está programada!
https://streamable.com/z66zxm

Ahora está en etapa de testeo de bugs, así que en el transcurso de la semana será subido a la Chrome Store y Mozilla Addons. 
¡saludos!

**Comment by emilianog94** [comment]
Testing exitoso, enviado a Chrome Store y Mozilla Addons, ¡muy pronto se actualizará en todos los navegadores!

**Comment by emilianog94** [comment]
Listo @Fede0GZ ! 
La funcionalidad ya forma parte de Steamcito desde la update v0.5. Te dejo el changelog acá: https://emilianog94.github.io/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/landing/changelog.html

Saludos, gracias!
