### ISSUE TITLE
[BUG] SteamDB separa los widgets de Steamcito

### ISSUE THREAD

**Issue by LeyendaV** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#90]
**Describí el bug**
El widget de estadísticas de SteamDB separa los widgets de Steamcito.

**¿Qué pasos seguiste para llegar al bug?**
Ejemplo:
1. Tener instalada la extensión de Steam DB (https://steamdb.info/extension/)
2. Entrar en la ficha de cualquier juego.

**Capturas de Pantalla**
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/7258518/654d4065-a5b1-4263-84e4-e26dc9874094)

**Información de tu PC**
 - Navegador que estás usando: Edge 119.0.2151.72
 - Versión de la extensión: SteamDB 3.7.8 - Steamcito 3.13

**Comment by emilianog94** [comment]
Hola @LeyendaV !

Gracias por avisar, no lo noté ya que no uso la extensión de SteamDB. 
Voy a ver cómo evitar este comportamiento en una próxima actualización.

Un saludo!

**Comment by emilianog94** [comment]
Hola @LeyendaV , te confirmo que se añadió esta mejora a la versión de Steamcito v.3.2.0 que se lanzará en el día de hoy. 

Un saludo y gracias!
