### ISSUE TITLE
[FEATURE] Desarrollar algo tipo web scrapper para obtener el valor del dolar en tiempo real

### ISSUE THREAD

**Issue by luchofmartinez** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#91]
Hola Emiliano, mucho gusto; Yo no sabia que existia esto de steamcito, hasta que desarrolle una app mobile y se la pase a mis amigos y me dijeron que existia tu aplicación. 
Te tiro una idea que quizás, yo lo implemente tambien pero como es un quilombo esto de los tipos de dolares aun no lo hice, que seria crear un webscrapper sobre la pagina del banco nacional o de alguna pagina oficial y tomar el valor del dolar que corresponda (blue, oficial, cripto, pachamama(? nose) y realizar el calculo.

Cualquier cosa, lo hablamos. Te dejo mi correo, luchofmartinez@gmail.com

Saludos

**Comment by emilianog94** [comment]
Buenas @luchofmartinez !

Te agradezco por la sugerencia! Te cuento que al menos por el momento no creí necesario crear un web scrapper para traer la cotización del dólar ya que existen endpoints públicos que traen las cotizaciones. 

Actualmente Steamcito utiliza un endpoint público de Ámbito Financiero que trae la cotización del dólar oficial cada una hora. Esta cotización está basada en el tipo de cambio referencial venta minorista elaborado por el BCRA: https://www.bcra.gob.ar/PublicacionesEstadisticas/Tipo_de_cambio_minorista.asp

Por esto mismo por el momento creo que no es necesario utilizar un web scrapper, aunque quien sabe, tal vez en un futuro la volatilidad sea mayor y una hora se quede corto y necesite hacer algo similar a lo que indicás vos o bien buscar algún otro endpoint actualizado más en el minuto a minuto!

Un saludo y gracias!
