### ISSUE TITLE
[BUG] Precio sugerido Incorrecto en productos de 19.99 USD

### ISSUE THREAD

**Issue by marianoag** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#92]
En helper.js el precio sugerido para 19.99 es 10.99 en vez de 10.49.

**Comment by emilianog94** [comment]
Mariano, te confirmo que en la actualización del día de hoy de Steamcito v.3.2.0 esto acaba de ser solucionado. 

Gracias!
