### ISSUE TITLE
[BUG] Precio en pesos argentinos no aparece

### ISSUE THREAD

**Issue by NachoXS15** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#93]
**Describí el bug**
Al ingresar a algunas paginas de juegos, el precio en ARS$ directamente no aparece.

**¿Qué pasos seguiste para llegar al bug?**
-Por ejemplo, entre a este juego: https://store.steampowered.com/app/1402110/Eternights/
-Al entrar, el juego muestra el precio en USD, y al hacerle click para mostrar el precio regional este no carga más y queda un espacio en blanco.
-Al querer hacer click para volver a USD, este queda ahi y no cambia.
-Al recargar la pagina, el error al querer ver el precio regional sigue ahí.

**Capturas de Pantalla**
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/86374911/695454b0-cf9c-4638-b35f-5ca7d384223b)

**Comment by emilianog94** [comment]
Buen día @NachoXS15 , muchas gracias por tu reporte!

Por el momento intenté pero no puedo replicar este bug que estás mostrando: 
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/87b13b45-6912-44de-b0e8-f11cf6d23593)


Te hago una pregunta: ¿En qué navegador y qué versión de Steamcito estás usando? Podés ver la versión clickeando el mate arriba a la derecha. 

Por otro lado, estando en la pantalla del bug, podrías pasarme una captura del log de errores? 
Para esto presionás F12 y clickeás en Consola/Console. Ahí deberían salir errores en rojo: 

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/83ce30d5-a40c-4c12-92c6-d66926f34cc7)


Gracias desde ya, quedo atento!

**Comment by emilianog94** [comment]
Te hago otra pregunta, ¿es en esa página de producto en particular o a partir de ahora te ocurre en todos los juegos que visitás?

**Comment by NachoXS15** [comment]
Wow, que rápido respondes jajaja

Actualmente estoy usando Google Chrome, te paso un video con todo lo que me pedis.


https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/86374911/38e4b592-7841-411b-8494-efa6affe2806

**Comment by emilianog94** [comment]
Justo estaba haciendo unas tareas de mantenimiento y me llegó tu issue 😁.

Muchas gracias por el vídeo, me re sirve para debuggearlo. 
En la semana voy a estar investigándolo para ver cuál puede ser la solución. 

Provisionalmente podés desinstalar la extensión y reinstalarla, con eso ya debería funcionar con normalidad.
¿Me informarías si vuelve a ocurrir? Esto me va a servir para ver qué tan frecuente puede ser el replicado de este error y si el desencadenante puede ser una sección particular que hayas visitado.

Gracias desde ya.

**Comment by emilianog94** [comment]
Gracias! Sí efectivamente toda la renderización de precios está relacionada con ese error. 
¿Me confirmás si tras desinstalar y reinstalar la extensión te vuelve a funcionar con normalidad?

**Comment by NachoXS15** [comment]
En efecto, reinstalar la extensión solucionó el problema!

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/86374911/74bf76dd-9732-4dd0-a49d-1284f6970186)

*me duele demasiado el precio*
