### ISSUE TITLE
[FEATURE] Agregar el precio original de un juego en oferta

### ISSUE THREAD

**Issue by manuelferreyra** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#94]
**¿Tu sugerencia se debe a un problema o dificultad que encontraste? Describilo**
Cuando esta en oferta un juego estaría bueno poder ver el precio original ya que ayuda a entender más que esta en descuento el juego

**¿Qué te gustaría que ocurra?**
Me gustaria que en los precios actuales se agregue el precio original tachado y al lado el precio que esta actualmente

**Alternativas que hayas considerado**
Solo la que marque anteriormente

**Comentarios Adicionales**
![ksAdYRy](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/74886093/47eecde7-118e-4f37-b459-10d8bfb030ff)

**Comment by Octaviorios** [comment]
Buenas! Venia a hacer el mismo ticket y vi que estaba este abierto. 

Si se puede sumar a la sugerencia de manuel (que me parece esta muy bien, y en un principio pensaba exactamente igual), despues de pensarlo un rato, diria que tal vez la seccion de la derecha no _deberia_ hacer ni siquiera referencia a cuestiones de descuento, ya que parece estar mas destinada a una comparacion de "regional sugerido por valve VS precio puesto por dev"

Tambien me di cuenta que mismo el porcentaje que dice "X juego es un x% mas caro/barato que lo sugerido por valve" tambien esta hecho basado en el precio corriente , que muchas veces (e incluso diria que la mayoria) puede ser de descuento, y no el "original", lo cual puede estar dando informacion "falsa" sin quererlo. Tal vez seria ideal hacer un nuevo parafraseo de toda esa seccion. Incluso tal vez mas simple de lo que hay ahora. 
 Aca dejo mi muy humilde aporte hecho en paint con 2 mangos, pero con amor, de como me imaginaria un posible parafraseo mas simple, y al mismo tiempo mas "certero" (segun mi criterio, obvio):

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/12775041/3624bff7-be9c-45e2-aac2-a6bbb8da0659)


Si se considera necesario hacer alguna aclaracion con respecto a un posible descuento corriente, tal vez se podria hacer algo asi:

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/12775041/c431fc16-02d9-4a16-9a8e-2ea29797a3fc)

Espero la sugerencia no moleste, obvio es una sugerencia nomas y desde ya gracias por leerla, un saludo!

**Comment by Octaviorios** [comment]
Porlas aclaro q ni me gaste en hacer las cuentas de los porcentajes jaja, era solo para dar un ejemplo. Saludos

**Comment by emilianog94** [comment]
Tarde pero seguro @manuelferreyra !

Confirmo que esta nueva funcionalidad ya es parte de Steamcito v3.50 para que el termómetro regional sea mucho más claro que en la actualidad. Esta nueva versión será lanzada en el transcurso de hoy.

![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/fc7d89cd-3942-4316-b62d-cd3ee57739c6)

Un saludo y gracias!
