### ISSUE TITLE
Consulta sobre versión de Firefox

### ISSUE THREAD

**Issue by Peanut84** [emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos#96]
En Firefox aun no se actualiza, probe desinstalando y reinstalando el plugin y nada. Sigue en la version 3.13. En Chrome si se actualizo

**Comment by marianoag** [comment]
Firefox tarda una semana en verificar la extension.

En Nigthly lo pude instalar, pero tuve que agregar una linea en manifest.json ademas de cambiar xpinstall.signatures.required a false en about:config.

Igualmente los cambios estan solo hechos en Chrome. Falta pasarlos a Firefox.

**Comment by Squaredude** [comment]
Te escribo a este issue porque está directamente relacionado.

Veo que empezaste a subir la extensión directamente en los releases, pero no se puede instalar en Firefox de forma manual porque faltan 2 cosas:

* el ID de la extensión en el manifest.json
* una "[firma](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/)" que solamente te la puede dar Mozilla

Por lo que pude leer (no soy dev de extensiones), si subís la extensión a Mozilla ellos la convierten y podrías bajar el XPI de ahí para ponerlo en los releases acá. Aunque no sé si es instantáneo o estamos en la misma situación de espera.

La alternativa desde nuestro lado es usar **Firefox Nightly**, ir a "about:config" y poner la configuración "`xpinstall.signatures.required`" en **`false`** para poder usar la extensión sin firmar.

De todos modos, otra cosa que me enteré mientras investigaba este tema, es que para que podamos usar la extensión incluso en **Firefox Nightly**, necesita el ID en manifest.json y además el archivo ZIP tiene que estar comprimido con "Deflate" o directamente sin compresión.

(El ID se puede sacar bajando la extensión de la página de Mozilla, abriendo el archivo y buscando casi al final de manifest.json la parte que dice `browser_specific_settings`. Se copia ese bloque y se pega al final de manifest.json del ZIP en releases.)

Yo directamente volqué todos los archivos a un directorio y lo volví a archivar, con el manifest.json editado, y lo instalé en Firefox Nightly, y puedo confirmar que funciona bien ahí.

**Comment by marianoag** [comment]
No me habia dado cuenta que estaban las extensiones para descargar, yo pensaba llenar un bug con la sugerencia para que este para descargar la extension de Firefox, pero cualquiera que use Nigthly puede comprimirlo por si mismo. Lo que si iba a hacer es un pull request para modificar el manifest.hson para agregar el id para no tener que hacerlo cada vez.

Yo pense que solo se podian las extensiones sin firmar en Nightly, pero tambien en Developer Edition (y ahora que lo pienso es logico) y aunque Developer sea mas estable que Nightly sigue siendo beta. Pero lo que me entere hace poco es que hay unbranded builds, asi que se pueden bajar la ultima version estable y modificando about:config instalar las extensiones sin firmar:

[Unbranded Builds](https://wiki.mozilla.org/Add-ons/Extension_Signing#Latest_Builds) 

El problema es que aunque sea la version estable, no se actualiza automaticamente asi que lo mas conveniente para usar la extension sin firmar es Developer (que aunque sea beta no es nightly y se actualiza automaticamente)

**Comment by Squaredude** [comment]
No la tenía a esa que había una versión entre estable y nightly. Gracias.

**Comment by marianoag** [comment]
Claro ahora la version estable es 120 y Nightly (version Alpha que sale todos los dias) 122. La beta y Developer edition (Beta pero con algunos cambios de flags y alguna otras  cosas) estan en 121

**Comment by Squaredude** [comment]
Podés creer que *recién* miro tu respuesta al OP y me di cuenta que ya habías dicho todo lo que dije ayer? 🤦🏻‍♂️

**Comment by marianoag** [comment]
En realidad no. Yo lo dije, pero no lo explique. El que lo leyo tendria que haber buscado lo que hay que modificar en manifest.json, pensaba hacer un pull request pero no lo hice. tal vez hoy a la noche con otras cosas mas.

**Comment by emilianog94** [comment]
> Te escribo a este issue porque está directamente relacionado.
> 
> Veo que empezaste a subir la extensión directamente en los releases, pero no se puede instalar en Firefox de forma manual porque faltan 2 cosas:
> 
> * el ID de la extensión en el manifest.json
> * una "[firma](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/)" que solamente te la puede dar Mozilla
> 
> Por lo que pude leer (no soy dev de extensiones), si subís la extensión a Mozilla ellos la convierten y podrías bajar el XPI de ahí para ponerlo en los releases acá. Aunque no sé si es instantáneo o estamos en la misma situación de espera.
> 
> La alternativa desde nuestro lado es usar **Firefox Nightly**, ir a "about:config" y poner la configuración "`xpinstall.signatures.required`" en **`false`** para poder usar la extensión sin firmar.
> 
> De todos modos, otra cosa que me enteré mientras investigaba este tema, es que para que podamos usar la extensión incluso en **Firefox Nightly**, necesita el ID en manifest.json y además el archivo ZIP tiene que estar comprimido con "Deflate" o directamente sin compresión.
> 
> (El ID se puede sacar bajando la extensión de la página de Mozilla, abriendo el archivo y buscando casi al final de manifest.json la parte que dice `browser_specific_settings`. Se copia ese bloque y se pega al final de manifest.json del ZIP en releases.)
> 
> Yo directamente volqué todos los archivos a un directorio y lo volví a archivar, con el manifest.json editado, y lo instalé en Firefox Nightly, y puedo confirmar que funciona bien ahí.


Buenas!

Efectivamente es tal como decís, el ZIP que subo al source solamente podría servir para instalarla como complementario temporario a través de _about:debugging_ porque no cuenta con la firma de Firefox para ser instalado. 

Efectivamente verifiqué esto que comentás y Firefox solamente la firma (y la convierte a formato XPI), cuando está aprobada. 

Ejemplo versión vieja 3.13: 
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/9bfac884-86dc-4ef7-a037-27adb3d7a90f)

Ejemplo versión nueva 3.21
![image](https://github.com/emilianog94/Steamcito-Precios-Steam-Argentina-Impuestos-Incluidos/assets/38828911/a5be0b1a-3f37-44cb-83f7-e573abf89a60)

¡Al parecer la única forma de instalarlo como complemento no temporario es con todo lo que indicaron acá! 
De mi lado espero que la aprueben pronto, la actualización fue enviada el día 13/12.

Un saudo!

**Comment by emilianog94** [comment]
La nueva versión de Firefox fue aprobada ayer 15/12! 
Cierro el issue
